### ISSUE TITLE
Opening browser on mouse hover

### ISSUE THREAD

**Issue by heldersepu** [mauve/vscode-terraform#101]
If I'm holding Ctrl and I mouse over a resource like `aws_instance` it launches the page:
https://www.terraform.io/docs/providers/aws/r/instance.html

I started noticing this when I was using Copy/Paste the browser will launch some times...
And is because after I select with the mouse and go for the `Ctrl+C` the mouse has slightly moved to a line that contains a resource, this bug is quite annoying to be honest.

**Comment by mauve** [comment]
please uninstall the `erd0s.terraform-autocompletion` plugin

**Comment by mauve** [comment]
reminder to self: add code to warn ppl who have that plugin installed.

**Comment by heldersepu** [comment]
That did it!

**Comment by heldersepu** [comment]
After disabling the terraform-autocompletion the F12 no longer works on resources...

**Comment by mauve** [comment]
@heldersepu please open a new bug for the F12 issue. Aside from the fact that that other plugin has been the source of more than a handful of *hovering opens browsers* issue reports I have no idea what the plugin does.
