### ISSUE TITLE
Show a warning if `erd0s.terraform-autocomplete` is installed

### ISSUE THREAD

**Issue by mauve** [mauve/vscode-terraform#102]
Installing this plugin triggers a bug which causes document link navigation to happen on Cmd/Ctrl+MouseOver rather than Cmd/Ctrl+Click, this bug gets reported to us every few weeks (examples: #111 #79 #67).

Since a few versions back the Terraform plugin now has autocompletion support (which is also more up to date). Therefore my recommendation is that the `erd0s.terraform-autocomplete` plugin is uninstalled or disabled in your installation.

**Comment by jcmartins** [comment]
I'm using release 1.3.4 and the problem continue.

**Comment by codnam007** [comment]
I uninstalled and my syntax highlighting and resource reference disappeared. These are features I love. I prefer your plugin so I reinstalled. 😄 
Would really love it if the bug was fixed though.

**Comment by mauve** [comment]
You are supposed to Uninstall the erd0s.terraform-autocomplete plugin, not my plugin.

**Comment by mauve** [comment]
@Fazered the link in the notification is added by VSCode I think, I will try to word it more clearly.

**Comment by Fazered** [comment]
Cool. Hopefully it will reduce the number of accidental uninstalls. Thanks for your work on the extension, I use it every day. Also thanks for finding a fix for this bug, it was driving me crackers!

My colleague next to me will not be happy that this bug won't effect me though. He found it hilarious when I grumbled about the dozens of bloody tabs I ended up opening!

**Comment by mauve** [comment]
Here is what the popup looks on my machine, as I am not a native speaker I am unsure how this can be worded more clearly, can somebody help?


![screen shot 2018-10-02 at 8 59 56 am](https://user-images.githubusercontent.com/795800/46333715-ab012700-c621-11e8-8e8a-b06cab78233e.png)

**Comment by Fazered** [comment]
Perhaps add a line like this?

Terraform (extension) is reporting this issue but DID NOT CAUSE IT.
