### ISSUE TITLE
New line added onsave for all tfvars

### ISSUE THREAD

**Issue by timm088** [mauve/vscode-terraform#105]
Looks like this has always been the behaviour
`hclfmt` go utility does not do this, so it seems to that it is behaviour directly in vscode / this plugin

Happy to assist with a pull request, looking for some assistance on what might be causing this before diving in.

**Comment by mauve** [comment]
What happens when you run 'terraform fmt ${path to file}'?

**Comment by timm088** [comment]
Yeh, same thing actually, it adds new lines ... looks like a terraform fmt issue as part of this https://github.com/hashicorp/terraform/issues/15607

**Comment by mauve** [comment]
as this is a bug in terraform itself I am now closing this. thanks for using my plugin and thanks for taking the time to report a bug.
