### ISSUE TITLE
Go to definition (F12) sending me to incorrect resource

### ISSUE THREAD

**Issue by heldersepu** [mauve/vscode-terraform#107]
Here is the example reproducing this issue:
https://github.com/heldersepu/hs-scripts/blob/38b532849614e737a26705043541c7a576712247/TerraForm/elb.tf#L3

Doing an F12 on the `app1` sends me to the `resource "aws_subnet" "test_app1"` instead of the actual resource that is on a different file

```
resource "aws_elb" "elb" {
  name    = "elb"
  subnets = ["${aws_subnet.app1.id}"]
  ...
}

resource "aws_subnet" "test_app1" {
  count      = 0
  vpc_id     = "${aws_vpc.myvpc.id}"
  cidr_block = "10.0.1.0/24"
}
```

**Comment by mauve** [comment]
thanks for the bug report, I am currently on vacation so it might take a week or so for a bugfix.

**Comment by heldersepu** [comment]
What? Vacation?!? 
I did not get the memo! I was under the impression that coders do not get vacations

**Comment by mauve** [comment]
I have pushed a fix but I will make the release next week so that I dont break stuff while being away.

**Comment by heldersepu** [comment]
No rush, it looks like one of your commits broke the build
