### ISSUE TITLE
Errors from .terraform folder

### ISSUE THREAD

**Issue by pecigonzalo** [mauve/vscode-terraform#108]
Hi! im trying to avoid this plugging from scanning and showing errors on my `.terraform` or other gitignored folders.
AFAIK, VSCode does ignore them, but i cant find a way to enforce this addon to do so.

Thanks.

**Comment by mauve** [comment]
you can configure ignored folders in the settings, what type of errors are you seeing?

**Comment by pecigonzalo** [comment]
@mauve There is no particular setting for terraform addon to ignore folders that im aware. Sorry I come from Subline and Atom and they default ignore gitignored folders from search, lint, format.

**Comment by mauve** [comment]
the setting is called `terraform.indexing.exclude` and it defaults to `[".terraform/**/*"]`

yes the naming is a bit weird.

**Comment by pecigonzalo** [comment]
@mauve I have it set to that but thought it was for something else, its set properly then.

Sometimes it still finds the errors... maybe its a VSCode issue, as I was just testing and for around 1 minute CSS linter was showing errors on an ignored `.venv` and now its gone...

Thanks for your help!

**Comment by mauve** [comment]
can you please post the errors you are seeing?

**Comment by mauve** [comment]
@pecigonzalo if you can find the errors, or if you get the behaviour again, please feel free to reopen or post to this bug, in the meantime I will close this issue
