### ISSUE TITLE
Multi-line string interpolation breaks syntax highlighting

### ISSUE THREAD

**Issue by Fiveside** [mauve/vscode-terraform#109]
Copying the example from the [terraform EKS getting started page](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html) breaks syntax highlighting.

<img width="712" alt="screen shot 2018-07-22 at 3 36 16 pm" src="https://user-images.githubusercontent.com/1858172/43050883-0f244f9a-8dc5-11e8-80b8-d4039511c108.png">

**Comment by squidfunk** [comment]
+1
