### ISSUE TITLE
Autocomplete deletes as I'm typing

### ISSUE THREAD

**Issue by cwcoffman** [mauve/vscode-terraform#110]
I can't use the extension, and have had to disable it.  As I type, the extension a) removes what I'm typing and b) puts it into the next section of terraform code.  I can't use autocomplete at all, because in the time it takes me to arrow down to the selection - the extension deletes everything and appends it to the section below.

Super frustrating as this extension has so many great features.  

Visual Studio Code 1.25.1 on Mac OS High Sierra.  Both up-to-date.

**Comment by mauve** [comment]
That sounds really annoying. Sorry  that you are experiencing problems.

Do you have format on autosave enabled (a terraform specific setting)? Can you please try it and disable format on autosave?

Is it possible for you to share a video?

Which other plug-ins do you have installed?


Kind regards,

Mikael

**Comment by cwcoffman** [comment]
Mikael;

You are awesome.  Seriously.  I love the extension and now it works!  And your response was so fast.

I couldn’t actually find an ‘autosave’ feature, but I did change the ‘formatonsave’ in terraform.format, as below.  That works.

    "terraform.format": {
        "enable": true,
        "ignoreExtensionsOnSave": [
        ".tfsmurf"
        ],
        "formatOnSave": **false**
    }


I can’t thank you enough for this.  Really awesome extension!
