### ISSUE TITLE
Documentation link error on MacOs

### ISSUE THREAD

**Issue by nascimento** [mauve/vscode-terraform#111]
When I pass my mouse pointer over resource name pressing COMMAND button the documentation automatically open.

For exemple, COMMAND+C to copy text open documentation.

```
resource '**aws_xxxx**' 'xxxx' {
}

```
Thanks

**Comment by mauve** [comment]
do you have the erd0s.terraform-autocomplete extension installed?

**Comment by mauve** [comment]
thanks for using my plugin, feel free to open the issue again if uninstalling the other plugin does not help.

kind regards,

Mikael

**Comment by nascimento** [comment]
Sorry man, yes I was using. 
Thanks

**Comment by mauve** [comment]
Thanks for getting back to me. This bug report is so common that I actually warn of the plugin is installed nowadays.

Thanks for using my plug-in.
