### ISSUE TITLE
Output panel constantly popping up

### ISSUE THREAD

**Issue by sthristov** [mauve/vscode-terraform#113]
Hi,

I updated the plugin to version 1.3.2 and the Output panel is popping up every time the indexing is started. I tries disabling the liveIndexing and the indexing as a whole but the panel is still popping up despite not starting the indexing. My VS Code version is 1.25.1.

Thank you

**Comment by mauve** [comment]
Hmm, it should automatically pop up whenever it logs a *WARN* or *ERROR* message? Can you please post the contents of your output view?

**Comment by mauve** [comment]
the `PATH` from your `.bash_profile` is only picked up if you launch code from your terminal

**Comment by sthristov** [comment]
Yep, thanks and sorry for the false alarm. :)
