### ISSUE TITLE
Inconsistencies between format document and save

### ISSUE THREAD

**Issue by aaronmell** [mauve/vscode-terraform#116]
I've enabled format on save. However, it seems to behaving inconsistently.

module "configuration" {
               source  = "path_to_module"
}

Ff I run save nothing happens here. source isn't moved back to the left.

If I run format document, the source is moved back to the left correctly

I get no errors in the terraform output when I save

**Comment by mauve** [comment]
Hi, thanks for your bugreport and thanks for using my extension.

What is your setting for `editor.formatOnSave` or `[terraform]editor.formatOnSave`?

**Comment by aaronmell** [comment]
I don't have editor.formatOnSave overridden, its set to false. I have [terraform]editor.formatOnSave to true

**Comment by aaronmell** [comment]
No, just the terraform plugin installed

**Comment by aaronmell** [comment]
Now it seems to be working. Can't explain it

**Comment by mauve** [comment]
Formatting is not performed if there is a syntax error in the file, or if the extension has not finished initializing yet (it can be a tad slow on large repository - working on improving that).

**Comment by aaronmell** [comment]
I think it might have been the syntax error, maybe I just wasn't noticing
it at the time. Happed around the same time I tried enabling format on save
after upgrading. Thanks for all the work you do, Terraform in VsCode is
better because of your plugin

**Comment by mauve** [comment]
closing, will doublecheck that formatting errors (if syntax errors) show up in the problems view though.
