### ISSUE TITLE
Formatting on save doesn't work

### ISSUE THREAD

**Issue by vide** [mauve/vscode-terraform#122]
Hello, thanks for the great plugin! I'm using VS Code 1.26.1 and vscode-terraform 1.3.4 and I can't get the plugin to run `terraform fmt` on the (manually) saved file as expected. The plugin does recognize the TF file and everything else works (syntax, autocompletion, peeking etc)  but the formatting on save.

In the output panel I only get 

`2018-08-20 10:13:57:403 [INFO ] file-system-watcher: Indexed file:///path/to/terraform/file.tf`

and nothing else. Just to be sure I've even specified 
```
    "[terraform]": {
        "terraform.format.enable": true
    }
```

in my VSCode User Settings. Any hint on how to debug this further?

**Comment by tsukune-ch** [comment]
Hello,
Formatting on save has been removed in vscode-terraform 1.3.0.
If you are using vscode-terraform 1.3.0 or later and use formatting on save, add the following setting to your user settings file.

```
"editor.formatOnSave": true
```

or

```
"[terraform]": {
    "editor.formatOnSave": true
}
```

Ref: https://github.com/mauve/vscode-terraform/blob/master/CHANGELOG.md#format-on-auto-save-removal

**Comment by vide** [comment]
Thanks @tsukune-ch I just read the main help page in the plugin section of VSCode, I missed the note in the readme.
```
"[terraform]": {
    "editor.formatOnSave": true
}
``` worked for me with 1.3.4.
