### ISSUE TITLE
Auto-format stopped working

### ISSUE THREAD

**Issue by scarolan** [mauve/vscode-terraform#125]
I'm not sure when this started but I am able to replicate it on a freshly installed Windows 10 instance.

Steps to reproduce:
1.  Download terraform, ensure it is in the user's PATH
2.  Install vscode and the vscode-terraform extension
3.  Edit a *.tf file, mess up the formatting.
4.  Save the file.  Auto-formatting doesn't work.

**Comment by audiolomb** [comment]
I think it's the new version of VSCode that broke it, but I might be mistaken.

**Comment by jkodroff** [comment]
I'm seeing the same behavior on macOS 10.13.8 with VS Code 1.27.1 and TF plugin 1.3.4.

Is there any chance that other plugins are interfering with this behavior, or are we confident that it's VS Code?

**Comment by mauve** [comment]
The output view (Shift-Cmd-U on Mac, Ctrl-Shift-U on Win) has a tab called
Terraform, please post the contents of that tab.

Kind regards,

Mikael

>

**Comment by audiolomb** [comment]
There is no such tab on mine...
![tf](https://user-images.githubusercontent.com/43075373/45555552-f62bd500-b7ed-11e8-9695-3ff80c647547.png)

**Comment by mauve** [comment]
Please click `Output` and then select `Terraform` in the drop-down on the right.
![screen shot 2018-09-14 at 4 32 17 pm](https://user-images.githubusercontent.com/795800/45556609-f81c8500-b83b-11e8-8c20-a1f0c6ac2898.png)

**Comment by audiolomb** [comment]
LOL, that was silly. Apologies!

 

Here’s the output:

 

2018-09-14 15:03:54:597 [INFO ] runner: Found Terraform binary terraform with version 0.11.8

2018-09-14 15:03:54:745 [INFO ] runner: Found Terraform binary C:\Program Files\Terraform\terraform with version 0.11.8

2018-09-14 15:03:54:871 [INFO ] runner: Found Terraform binary terraform with version 0.11.8

**Comment by mauve** [comment]
that looks weird, can you please post the value of your `PATH` environment variable? Pasting the following in PowerShell will show the value of the `PATH`: `Get-ChildItem Env:Path` (I think just writing `$Env:Path` also works).

**Comment by mauve** [comment]
@scarolan @jkodroff can you please post your contents of the `Output` > `Terraform` view?

**Comment by audiolomb** [comment]
@mauve here is my env variables
![env](https://user-images.githubusercontent.com/43075373/45626558-b3b00580-ba44-11e8-950a-1158358d62d0.png)

**Comment by george-richardson** [comment]
I recently noticed the same after not using terraform for a while. For me it was the jump to version 1.3 which includes the change "Format On Auto-Save Removal", I did not have the setting "editor.formatOnSave" set to true so the removal of "terraform.format.enable" setting broke any formatting for me. This problem was compounded by the README.md on this repo still referencing the "terraform.format.enable" setting. I only worked out what was happening by downgrading my extension to older versions to find exactly where it broke and then looking at the changelog. 

So quick-fix for me was to add `"editor.formatOnSave": true` to my user settings. I think the README for this extension should be updated to include this requirement as this setting's default on a new install is false.

**Comment by mauve** [comment]
I am going to close this bug due to inactivity. Please feel free to open again.

Thanks for using my plugin and thanks for taking the time to open bugs.

**Comment by MacTynow** [comment]
Hi @mauve, Thanks a lot for your plugin!

 I'm running into the same issue.
vscode version : 1.30.1
vscode-terraform version : 1.3.5

I have `editor.formatOnSave` set to `true` in my user settings. 
Here is the output from the terraform tab :
```
2019-01-03 05:29:31:346 [INFO ] formatting-provider: running 'terraform fmt' on '/Users/mactynow/terraform/aks-demo/main.tf'
2019-01-03 05:29:31:346 [INFO ] runner: Running terraform cwd='/' path='/usr/local/bin/terraform' (version: 0.11.10) args=[fmt, -]
2019-01-03 05:29:32:179 [INFO ] runner: Running terraform succeeded.
2019-01-03 05:29:32:300 [INFO ] file-system-watcher: Indexed file:///Users/mactynow/terraform/aks-demo/main.tf
```

I am also running the azure-terraform plugin, could there be conflicts ? 

Let me know if I can do anything to help.

**Comment by queglay** [comment]
I'm having issues with terraform format on save now.  I also cannot right click and format manually.  I have format on save enabled in the preferences.

**Comment by mauve** [comment]
Is the language set to Terraform for your files, or is it set to HCL?

**Comment by queglay** [comment]
Its set to terraform


Andrew Graham

**Comment by pixelicous** [comment]
First of all thanks very much for the extension!
I also have issues with format on save on vscode 1.31.1
I have the latest version installed of the extension

I can right click and choose format document and it will work, my settings look like this (with non related details removed):
{
    "terraform.format": {
        "enable": true,
        "ignoreExtensionsOnSave": [
            ".tfsmurf"
        ],
        "formatOnSave": true
    },
    "terraform.codelens.enabled": false
}

**Comment by alexismosquera** [comment]
Hi all.
Terraform plugin for vscode is not working anymore :-(
This is the vscode information:
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic

No ouput information in the vscode console.  Any of its functionalities is working.  I'm using the extension version 1.3.9.

Please, fix it.

**Comment by pixelicous** [comment]
@alexismosquera You basically uninstalled :)

**Comment by smiller171** [comment]
If anyone is wishing for automatic formatting back, this will do it for you. It uses fswatch to pass files to `terraform fmt` on save

```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Terraform Format",
      "type": "shell",
      "command": "fswatch -r -e terraform/.terraform --format %p terraform | xargs -n1 -I{} terraform fmt {}",
      "group": "test",
      "presentation": {
        "echo": false,
        "reveal": "never",
        "focus": false,
        "panel": "shared",
        "showReuseMessage": false,
        "clear": true
      },
      "runOptions": {
        "runOn": "folderOpen"
      }
    }
  ]
}
```
