### ISSUE TITLE
Disable References

### ISSUE THREAD

**Issue by kagarlickij** [mauve/vscode-terraform#128]
Hi there,
Is it possible to disable displaying References in editor? 
Sometimes it's handy, but sometimes not.
Thanks in advance!

**Comment by mauve** [comment]
I think the setting is called terraform.codelense something.

**Comment by kagarlickij** [comment]
@mauve thanks, it did worked!

**Comment by orlando** [comment]
Just in case is not working for others, you need to restart vscode in order for this change to work

**Comment by macecchi** [comment]
For anyone else looking for the exact setting:
`"terraform.codelens.enabled": false`

Found it here https://github.com/mauve/vscode-terraform/commit/f8566c0ec070c53a76bfe270c98149adb930da1d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R156

**Comment by QuotableWater7** [comment]
I want to say first that I love `vscode-terraform`, but the references feature is extremely annoying. I'd suggest having it disabled by default.
