### ISSUE TITLE
terraform statement without a required_version attribute

### ISSUE THREAD

**Issue by ldormoy** [mauve/vscode-terraform#132]
Hi,

I opened my terraform repo today with vscode and got 360 problems about a missing required_version attribute.

How do I disable this check?

Thanks :-)

**Comment by ldormoy** [comment]
Well it's because it also includes my /.terragrunt-cache /* subdirectories (which should not happen). They are in my .gitignore but apprently still indexed by the plugin.

I use a multi-account, multi-region structure, like this: account/region/family/component

What do you mean exactly with template/workspaces?

**Comment by mauve** [comment]
You can use `terraform.indexing.exclude` to ignore paths from indexing. It might make sense to also look at `.gitignore` but I do not do that right now.

**Comment by ldormoy** [comment]
Thanks for the indexing tip, now I only have 16 notifications

**Comment by msaraceno** [comment]
+1 for me as well, I have 61 problems related to "statement without a required_version attribute" do you have an ETA of when you will be updating?

**Comment by mauve** [comment]
will hopefully update today

**Comment by arnvid** [comment]
Hi 

This error comes from every single state.tf file that we use in our projects.

`
terraform {
  backend "s3" {
    key = "environmen/service/terraform.tfstate"
  }
}
`

**Comment by mauve** [comment]
Fixed in 1.3.6
