### ISSUE TITLE
Terraform: show plan error

### ISSUE THREAD

**Issue by harkamals** [mauve/vscode-terraform#135]
When I try to run 'Terraform: show plan' from command pallet:
command 'terraform.show-plan' not found.

Using max osX, latest vscode

**Comment by osterman** [comment]
Same here! Any resolution? Using vscode 1.30.1 on Amazon Linux .

**Comment by knabb** [comment]
I'm noticing the same issue.

**Comment by donkeyx** [comment]
I am guessing no progress on this, considering this bug was raised in January. Having same issue with any pallet commands.
