### ISSUE TITLE
Option to disable fmt for tfvars file

### ISSUE THREAD

**Issue by dmlemos** [mauve/vscode-terraform#14]
The terraform fmt runner is neat, but on I would prefer to have an option to disable it for `tfvars` file. It makes them look really ugly with spaces between all the variables.

**Comment by frosas** [comment]
Not sure if it's a new feature, but I see what's requested is already possible:

```js
"terraform.format": {
    "ignoreExtensionsOnSave": [
      ".tfvars"
    ]
  }
```
