### ISSUE TITLE
formatting-provider: formatting failed. TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by hylaride** [mauve/vscode-terraform#144]
Recently, terraform fmt has stopped working with the following error:
```
2018-11-15 14:46:00:470 [INFO ] formatting-provider: running 'terraform fmt' on '/Users/REMOVED/REMOVED/terraform/provider_versions.tf'
2018-11-15 14:46:00:471 [ERROR] formatting-provider: formatting failed. TypeError: Cannot read property 'path' of null
```

I'm at a loss for what to try next. I'm on 1.29.0 of VSCode and 1.3.7 of the terraform module

**Comment by mauve** [comment]
what does your configuration look like?

**Comment by heldersepu** [comment]
I'm on a similar boat but for me it just does not format at all I do not get any errors...
1.29.0 of VSCode 
0.2.2 of Azure Terraform
1.3.7 this module

**Comment by hylaride** [comment]
@mauve 
```
    "[terraform]": {
        "editor.tabSize": 2,
        "editor.formatOnSave": true
    },
```

My global is set as ```    "editor.formatOnSave": true,```

**Comment by mauve** [comment]
Is that the only configuration you have for the terraform plugin?

/M

**Comment by heldersepu** [comment]
The `"editor.formatOnSave": true` did it for me...
strange this is disabled by default

**Comment by heldersepu** [comment]
@hylaride try doing a `terraform fmt` from the console see what you get...

**Comment by hylaride** [comment]
So PEBKAC, but it was a very strange issue.  My `tfenv` was b0rked, but it worked fine from iterm and the integrated terminal in VSCode.  it was only when I tried to do install the latest terraform binary with `tfenv` that I saw the issues. I had to do a complete re-install of tfenv to fix it.  I'm going to close this off as to not waste any more of your time! :-)

**Comment by hussfelt** [comment]
I am reopening this. Have the same issue and I am not running tfenv.

The solution is to create a .bash_profile as it seems it would run bash even if you define another shell.

In the below example I am adding `$HOME/bin` to the `$PATH` as that's where I keep terraform.

```# cat ~/.bash_profile
export PATH=$HOME/bin:/usr/local/bin:$PATH```

Error:
```2018-11-20 10:33:52:346 [ERROR] formatting-provider: formatting failed. TypeError: Cannot read property 'path' of null```

Terraform fmt worked from terminal within VSCode and in iTerm.

* Version 1.29.1 (1.29.1)
* Terraform v0.11.10
* vscode-terraform 1.3.7

These are my User Settings:
```
{
    "terminal.integrated.shell.osx": "/bin/zsh",
    "editor.formatOnSave": true,
    "[terraform]": {
        "editor.formatOnSave": true
    }
}
``´

**Comment by dooreelko** [comment]
ok. awkward, but restarting vscode seems to solve this.
(i aslo touched the source code of terraform extention, but adding this.log statements definitely wasn't supposed to make a difference)
