### ISSUE TITLE
Unable to locate executable file: 'terraform'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

### ISSUE THREAD

**Issue by pravisivadasan** [mauve/vscode-terraform#145]
i am trying to provision vm using terraform in azure devops. i had setup the release task in pipline. when am running the pipeline getting error like
Unable to locate executable file: 'terraform'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

Can any one help me to solve this.

**Comment by shreedhargowda** [comment]
I am having the same Issue.
