### ISSUE TITLE
Trimmed variables' names,  missing references, broken autocomplete

### ISSUE THREAD

**Issue by szymonbr** [mauve/vscode-terraform#148]
It's not possible to use autocomplete for variables because the addon trims its name by first and last char.
For instance `variable instance_type {}` is recognized as `nstance_typ`. Hence using autocomplete is useless. Also it causes that finding references does not work correctly due to variable name not matching.
Attached the screenshot with the bug preview.
It concerns 1.3.7 version of Terraform extension with VS Code 1.30 on Mac OS 10.13.6.
If anybody know any solution or a workaround or just faced the same issue please confirm in this issue.
<img width="509" alt="terraform-extention-issue-vs-code" src="https://user-images.githubusercontent.com/45372752/50795220-ce490b80-12cd-11e9-9486-b5801346f018.png">

**Comment by innovia** [comment]
👍 
![image](https://user-images.githubusercontent.com/112025/50837704-f6d01480-1364-11e9-9cf8-91855310ac91.png)

**Comment by innovia** [comment]
OK the issue for me is that the variable name must use surrounding quotes (i believe i saw that mentioned somewhere and ignored it)

**Comment by innovia** [comment]
@szymonbr your variable name is not surrounded with quotes. i think you can close this issue

**Comment by szymonbr** [comment]
Thankt @innovia . You are totally right. I confirm there were missing quotes. I've corrected the code and now all references are ok. 
By the way the corrections have been made very easy with [Wrap Selection](https://marketplace.visualstudio.com/items?itemName=konstantin.wrapSelection#overview) tool. Just double clicked on a variable, typed quote, and done - opening and closing quote done with two clicks only!  Probably you may find may other tools which do the similar. But that one did the great job. :)
