### ISSUE TITLE
Document Formatter

### ISSUE THREAD

**Issue by iancward** [mauve/vscode-terraform#149]
I was trying to run "Format Document" from the command palette I got a warning that there was no document formatter for hcl-files installed. I found https://github.com/mauve/vscode-terraform/blob/master/CHANGELOG.md#format-on-auto-save-removal in the CHANGELOG; however, the README for this repository claims that this project support formatting https://github.com/mauve/vscode-terraform#formatting-support.

I can't really figure out if message in the CHANGELOG just says that the built-in autoformatter was removed and that VS code-provided formatting should still work, or terraform files can't be formatted at all any more.

For reference, I'm running VS code version 1.30.2 and terraform extension version 1.3.7.

**Comment by mauve** [comment]
you need to check that you have associated this plugin with your file and
file-ending, I don't think the plugin is associated with .hcl files only
.tf files, you can configure that manually in your settings.

**Comment by iancward** [comment]
When I open a .tf file in VS Code, it shows up as an HCL language file. I don't believe I ever did anything to change it from terraform or tf.

I switched the file to "terraform" and it looks like things actually work now. Huh, I guess I was missing out. Maybe update the README to tell users to make sure they've selected "terraform" code type and not "HCL" (which is technically what terraform code is written in).

Thanks!

**Comment by iancward** [comment]
Well, all the new .tf files that I open are coming up at HCL files. Is there something I need to change to make it default to a terraform file? Or maybe something I changed initially to make it show up as an HCL file instead of terraform?
I've tried uninstalling and reinstalling the extension and I'm seeing the same behavior.

**Comment by mauve** [comment]
thanks for your bug report, there is another plugin which adds HCL support which you should uninstall as it breaks my plugin.

thanks for using my plugin.
