### ISSUE TITLE
Question about Templates

### ISSUE THREAD

**Issue by pecigonzalo** [mauve/vscode-terraform#150]
Hi! Im trying to understand what the addon refers as "templates". Are this templates for autocompletion/snippets? 

Thanks!

**Comment by mauve** [comment]
If you are referring to the `terraform.templateDirectory` setting, then, by
templates I mean your terraform files. The has been with the plugin since
the early days when I was still a big Terraform noob so the nomenclature
might be incorrect.

/M

**Comment by pecigonzalo** [comment]
Mauve, yes I was referring to that setting. I was unsure if it meant a "modules" directory or something. So it uses `currentDir` + `terraform.templateDirectory` ? 

I was wondering as I was trying to check/add support for modules. I can parse them easily from Python but I have 0 knowledge of TS, and cant find a HCL parser.
It would be lovely to get autocompletion from vars/output of modules, but for that I want to first understand how this works :D

**Comment by mauve** [comment]
The index module in the source for the add on handles HCL parsing and building a index of TF files.

Autocompletion does not yet use it though (autocompletion-provider.ts) also that file is a huuge hack.

Happy coding.

**Comment by pecigonzalo** [comment]
Excellent, we can close this. Thanks!
