### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Chi-eze** [mauve/vscode-terraform#151]
- Issue Type: `Performance`
- Extension Name: `terraform`
- Extension Version: `1.3.7`
- OS Version: `Linux x64 4.4.0-141-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/podosky/mauve.terraform-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mauve** [comment]
should be fixed by 1.3.8

Thanks for using my plugin, feel free to reopen if 1.3.8 does not fix this issue.
