### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dgellow** [mauve/vscode-terraform#156]
- Issue Type: `Performance`
- Extension Name: `terraform`
- Extension Version: `1.3.7`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

[mauve.terraform-unresponsive.cpuprofile.txt](https://github.com/mauve/vscode-terraform/files/2906090/mauve.terraform-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

(Pull request created following an alert from Visual Studio Code)

**Comment by mauve** [comment]
should be fixed by 1.3.8

Thanks for using my plugin, feel free to reopen if 1.3.8 does not fix this issue.

**Comment by dgellow** [comment]
Nice, tank you
