### ISSUE TITLE
Fmt on save not working with vscode 1.11.1

### ISSUE THREAD

**Issue by commarla** [mauve/vscode-terraform#16]
Hi,

Thanks for the good work on this extension.
Since the last update of vscode, the fmt on save doesn't work anymore. I have update to 0.0.7 and added  `"terraform.formatOnSave": true` to my use settings.

My coworker has the same problem.

Laurent.

**Comment by jharley** [comment]
I'm seeing the same thing with 0.0.7 using Code 1.11.1

**Comment by mauve** [comment]
Sorry for the breakage, however this is a bit weird as it works on `vscode 1.11.1` with `0.0.7` for me.

My terraform settings are:

```
terraform.formatOnSave: true,
terraform.formatVarsOnSave: null,
terraform.path: /Users/mauve/.bin/terraform
```

It works for both `.tfvars` and `.tf` files for me.

Can you please post your settings? Is it broken for all terraform files or for just `.tf` or `.tfvars`?

**Comment by jharley** [comment]
Huh!  Looks like `terraform.formatOnSave` got changed to "false"?!  It's been working for months :\

It's working now that I changed the setting.. but I wonder how/why it got swapped?

**Comment by andrewmeissner** [comment]
My user settings are 

```json
    "terraform.path": "/usr/local/bin/terraform",
    "terraform.formatOnSave": true,
```
and I still can't format on save.  :(  

VsCode 1.11.1
vscode-terraform 0.0.8
terraform v0.8.8

**Comment by mauve** [comment]
the default configuration for `formatOnSave` used to be `true` but I changed it to `false` for `0.0.6` that might have caused some confusion.

@andrewmeissner do you only need the other plugin because it also handles `.hcl` files? I haven't seen files with the `.hcl` ending before so I can just add it.

#17

**Comment by commarla** [comment]
I confirm @andrewmeissner answer, vscode-terraform and wholroyd.HCL can't work together anymore. It was working before.

**Comment by commarla** [comment]
I don't remember why I have wholroyd.HCL installed. I have disabled it and I am fine.

**Comment by mauve** [comment]
I just released a version which also handles .hcl files, if I got this correctly the only thing missing from the Terraform plugin was that, I will close this bug now.

Thanks for reporting!

**Comment by commarla** [comment]
@andrewmeissner workaround here https://github.com/mauve/vscode-terraform/issues/18#issuecomment-293820721
