### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by manojs888** [mauve/vscode-terraform#164]
Hi, I am looking for the functionality that is offered by the default intellij plugin for terraform. One of the most important features it offers is its ability to transverse the code and highlight sections, variables and so forth. I have not been able to produce the same on VSC - tf plugin. Maybe it is there and more but the documentation, etc is not simple for me, pls advise as I would love to swap over, thank you

**Comment by mauve** [comment]
I do not really know what you are referring to, can you send a screenshot or something similar?
