### ISSUE TITLE
reference count and go to definition not working for modules

### ISSUE THREAD

**Issue by heldersepu** [mauve/vscode-terraform#165]
The reference count for modules does not seem to be working:

<img width="420" alt="bug_tf" src="https://user-images.githubusercontent.com/545474/54713859-023e7980-4b26-11e9-9203-a8fec1c99909.png">

You can see in the image that the `module "bucket11" ` shows `0 references` but that is clearly referred in line 14 `one = "${module.bucket11.enabled}"`
https://github.com/heldersepu/hs-scripts/blob/master/TerraForm/example.tf

Also the go to definition does not work when I do it on the `module.bucket11`

**Comment by heldersepu** [comment]
Looking at the unit tests, there are check for:
- [variable references](https://github.com/mauve/vscode-terraform/blob/2dcf68f8d0b1f2571e1e2cdc6f55676acfd3da5d/test/index/reference.unit.test.ts#L21)
- [data references](https://github.com/mauve/vscode-terraform/blob/2dcf68f8d0b1f2571e1e2cdc6f55676acfd3da5d/test/index/reference.unit.test.ts#L31)
- [resource references](https://github.com/mauve/vscode-terraform/blob/2dcf68f8d0b1f2571e1e2cdc6f55676acfd3da5d/test/index/reference.unit.test.ts#L41)
- [locals references](https://github.com/mauve/vscode-terraform/blob/2dcf68f8d0b1f2571e1e2cdc6f55676acfd3da5d/test/index/reference.unit.test.ts#L51)

nothing about module references, I guess that was never implemented

**Comment by mauve** [comment]
module references (and autocomplete) have not yet been implemented.

**Comment by heldersepu** [comment]
How hard do you think it will be?
I wanna help ... were should i start?
