### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by Rick-2CA** [mauve/vscode-terraform#170]
I'm experiencing high cpu utilization with v1.3.9 on first open or when any changes to a VSCode workspace are initiated.  The process rg.exe goes to town causing a period of time where it can impact system usage.  Disabling indexing didn't impact the performance hit.

Running Windows 8.1

vscode -v:
```
1.33.1
51b0b28134d51361cf996d2f0a1c698247aeabd8
ia32
```
code --list-extensions --show-versions
```
christian-kohler.path-intellisense@1.4.2
CoenraadS.bracket-pair-colorizer@1.0.61
DavidAnson.vscode-markdownlint@0.26.0
emilast.LogFileHighlighter@2.4.3
formulahendry.auto-close-tag@0.5.6
kumar-harsh.graphql-for-vscode@1.13.0
**mauve.terraform@1.3.9**
mechatroner.rainbow-csv@1.0.0
ms-vscode.powershell@1.12.0
nachocab.highlight-dodgy-characters@1.0.0
redhat.vscode-yaml@0.4.0
wengerk.highlight-bad-chars@0.0.3
```

**Comment by mauve** [comment]
Without more data I cannot debug your problem, please follow the steps here:

https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load
