### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by agpenton** [mauve/vscode-terraform#171]
- Issue Type: `Performance`
- Extension Name: `terraform`
- Extension Version: `1.3.9`
- OS Version: `Linux x64 5.0.6-200.fc29.x86_64`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/agpenton/mauve.terraform-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by mauve** [comment]
Missing `cpuprofile.txt` file, closing bug report.

Thanks for using my plugin and I am sorry that it doesn't work as expected for you without the profile data I cannot debug further.
