### ISSUE TITLE
Extension doesn't work as expected

### ISSUE THREAD

**Issue by alexismosquera** [mauve/vscode-terraform#173]
When I close and open my VS Code the extension doesn't work anymore.  I have to uninstall it and install it again.  The other issue is when I open a second instance of my VS Code, with it, the extension works in the 1st instance but not in the 2nd.

Please fix it.  It is a great extension.

I'm using:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

And:
Visual Studio Code:
Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-48-generic

**Comment by mauve** [comment]
Sorry that it isn't working for you, I cannot reproduce your problems.

Which other plugins do you have installed?
