### ISSUE TITLE
Contributing guide?

### ISSUE THREAD

**Issue by pselle** [mauve/vscode-terraform#175]
I'm looking for information on contributing, or docs on how to test/contribute to this extension.

**Comment by mauve** [comment]
Hi

Thanks for taking the time to contribute to my plugin.

I wrote this guide a while back https://github.com/mauve/vscode-terraform/blob/master/BUILDING.md which should cover most things, please let me know if you hit any problems.

**Comment by pselle** [comment]
Thank you for the pointer! Missed that -- this could be closed, or I wonder if it's useful to move that to a `CONTRIBUTING.md` since that's the convention? (although, I see BUILDING really is about BUILDING)

**Comment by mauve** [comment]
Maybe we could start by adding a CONTRIBUTING.md which just points to
BUILDING.md until there is better content? I don't have time to spend right
now so if you want to contribute I would very much appreciate it.

Thanks.

:)

**Comment by mauve** [comment]
closing for now, thanks for you interest and I am looking forward to your contributions.
