### ISSUE TITLE
Unknown token: IDENT string

### ISSUE THREAD

**Issue by yjpa7145** [mauve/vscode-terraform#179]
I am using vscode-terraform 1.3.11 with this Terraform configuration:

```terraform
variable "prefix" {
  type = string
}
```

That is producing this error in the PROBLEMS tab:

`Unknown token: 2:10 IDENT string [2,10]`

As far as I can tell from the [Terraform Documentation](https://www.terraform.io/docs/configuration/variables.html#declaring-an-input-variable), this should be valid.

If I run the same code through `terraform validate` and `tflint`, I get no reported errors:

```
$ terraform validate
Success! The configuration is valid.

$ tflint
Awesome! Your code is following the best practices :)

$ terraform --version
Terraform v0.12.0
+ provider.aws v2.12.0

$ tflint --version
TFLint version 0.8.0
```

I have both `terraform.lintPath` and `terraform.path` set to point to the correct versions of `terraform` and `tflint`.

**Comment by mauve** [comment]
terraform 0.12 syntax is not yet supported, see issue #157

**Comment by yjpa7145** [comment]
Thanks for the quick reply, I'll follow that thread.

**Comment by rbarrimond** [comment]
This is annoying and I believe it is affecting how codelens is working.

**Comment by wbuehler9909** [comment]
Still an issue, seeing type = list(string) as invalid, code runs with no issues

**Comment by kevanlucc** [comment]
Having this issue as well, code runs but VScode gives me an error (Unkown token: IDENT string).

**Comment by dotnetcanuck** [comment]
Having this issue as well, latest versions of VSCode + extension + language server.

I love the auto complete functionality, but these random errors are extremely irritating, especially for someone who is trying to learn Terraform for the first time.

**Comment by jeffwalsh** [comment]
also getting these errors. for now i just turned off the linter by going to the settings and changing tflint binary to empty.
