### ISSUE TITLE
Add an option to force hcl hightlighting to any files

### ISSUE THREAD

**Issue by commarla** [mauve/vscode-terraform#18]
Hi,

As mention in https://github.com/mauve/vscode-terraform/issues/16. I remembered why I had installed [HCL](https://github.com/wholroyd/vscode-hcl) extension.

Without it I can't force the syntax highlighting on any file extension.

I have some *.hcl files but with *ctmpl extension (for consul template). With the HCL extension I can choose to force vscode to recognize those files as hcl and without I can't: 
<img width="811" alt="screenshot 2017-04-13 07 38 30" src="https://cloud.githubusercontent.com/assets/4509360/24991593/3f7b184e-201c-11e7-9c85-581d57d443b2.png">

Do you think you can make it?
It would be great.

Laurent

**Comment by commarla** [comment]
Some files are hcl but not terraform, I am thinking about nomad files. So we can't apply a `terraform fmt` on it. You're plugin was design for terraform and not for all hcl files.

The fmt should apply only on tf and tfvars files. The syntax highlight to any other files.

**Comment by mauve** [comment]
Absolutely will release a fix shortly.

**Comment by commarla** [comment]
With the following setting 
```
"files.associations": {
    "*.ctmpl": "hcl",
    "*.tf": "terraform",
    "*.tfvars": "terraform"

},
```
I can work with both extensions enabled. But I'd rather have only one :-).
Thanks for your work.

**Comment by commarla** [comment]
Yeah! Thanks a lot!

**Comment by andrewmeissner** [comment]
Thanks
