### ISSUE TITLE
Add option to disable linting

### ISSUE THREAD

**Issue by blairham** [mauve/vscode-terraform#182]
While the work on getting terraform 0.12 working, it would be nice to have the option to disable linting but keep all the other features that this plugin provides.

**Comment by mauve** [comment]
you can disable these feature by having this config:

```
{
  "terraform.indexing": {
    "enabled": false,
    "liveIndexing": false,
    "exclude": ["**/*"]
  },
}
```

the `exclude` part is the important part of the config, in the meantime if somebody can make a PR which disables these features by default that would be nice.
