### ISSUE TITLE
v1.3.12 - CodeLens and Terraform Explorer doesn't working

### ISSUE THREAD

**Issue by dminella** [mauve/vscode-terraform#185]
Unfortunately both "codelens" and "terraform explorer" aren't working.

Examples:

1. CodeLens doesn't show variable references.
2. Terraform Explorer loading forever.

**Comment by mauve** [comment]
We do not support TF 0.12 yet so this might be the error you are seeing, please update with more information about any errors and the setup you have.

**Comment by dminella** [comment]
Sure, I downgraded tf'v version. Thank you!
