### ISSUE TITLE
String highlighting error

### ISSUE THREAD

**Issue by marc-costello** [mauve/vscode-terraform#19]
Since the most recent update (0.8 or 0.10 not to sure), it seems to have introduced a bug in the syntax highlighting of strings.

The attached screenshot explains it better:

![screen shot 2017-04-13 at 08 15 46](https://cloud.githubusercontent.com/assets/4884262/24994221/c1b45802-2021-11e7-9ebe-3d033d372720.png)

After the `DEFINITION` string ends, the highlighting is treating the rest of the file as a string, when it is not.

The Terraform template is definitely valid and it's not an escaping issue, the problem first occurred after I updated the plugin.

**Comment by commarla** [comment]
Hi @marc-costello ,

I think `DEFINITION` is not correctly indented. You need to remove the indentation.

**Comment by marc-costello** [comment]
You're right, so you know when I said the template is valid, right...
It was working as expected prior to the update but it's okay - Thanks for clearing that up!

**Comment by mauve** [comment]
According to my limited understanding of this HCL I think @commarla  is correct, the end-marker of the heredoc needs to be in column 0. Refer https://github.com/hashicorp/hcl/blob/39fa3a62ba92cf550eb0f9cfb84757ef79b8aa30/hcl/parser/parser_test.go#L27
