### ISSUE TITLE
Linting error using file function

### ISSUE THREAD

**Issue by soupdiver** [mauve/vscode-terraform#192]
My block looks like:
```terraform
provisioner "remote-exec" {
    script = "../setup-docker.sh"
    connection {
      type = "ssh"
      host = "${aws_instance.w1.public_ip}"
      user = "ubuntu"
      private_key = file("${var.provisionKeyPath}")
      agent = false
    }
  }
```

Terraform uses it without any problem but I get a syntax error in VSCode: `Unknown token: 87:21 IDENT file`

I'm using version `1.3.12`

![Screenshot 2019-06-24 at 10 28 30](https://user-images.githubusercontent.com/800562/60003381-de318d80-966a-11e9-94e6-96e5ea0ee274.png)
![Screenshot 2019-06-24 at 10 28 42](https://user-images.githubusercontent.com/800562/60003382-de318d80-966a-11e9-8878-f97c68245b47.png)

**Comment by mauve** [comment]
this is a terraform 0.12 feature which is not supported yet see #157 for progress

**Comment by soupdiver** [comment]
Closign then in favor for #157
