### ISSUE TITLE
Formatting a multiline function call only _almost_ does the expected thing

### ISSUE THREAD

**Issue by tomasaschan** [mauve/vscode-terraform#208]
Given this code:
```
locals {
  example = format("hello, %s! this is an %s of %s doing weird stuff",
    "terraform",
    "example",
  "format")
}
```
I would have expected the formatting command to indent `"format")` to the same level as `"example",`, but the snippet above is the formatted output.

If I add a newline before the ending parenthesis, the rationale behind this becomes a little more obvious - the formatted document now looks like this:
```
locals {
  example = format("hello, %s! this is an %s of %s doing weird stuff",
    "terraform",
    "example",
    "format"
  )
}
```
It would be nice if the formatter knew to insert that newline, so I don't have to. It took me a while to figure out what I had to do to make this code format nicely 😄

**Comment by mauve** [comment]
Formatting is done by calling 'terraform fmt'. Please reopen this bug in the terraform repository.

Thanks for using my plugin.

**Comment by tomasaschan** [comment]
Ah, sorry for the noise!
