### ISSUE TITLE
terraform.tfvars An argument named "xxx" is not expected here.

### ISSUE THREAD

**Issue by fredflev** [mauve/vscode-terraform#218]
I am having the following problem/false postive reported by the `vscode-terraform` extension for all variables defined in `terraform.tfvars` files: 

`An argument named "XXX" is not expected here.` 

![image](https://user-images.githubusercontent.com/42792052/65577388-495e6900-dfa6-11e9-824e-acd3dbb0ed23.png)

Is there a setting I can set in `settings.json` to prevent the extension from checking for this in all `terraform.tfvars` files? Is there a way to know what rule/check of the `vscode-terraform` extension is triggering this? 

My vscode settings for the terraform extension are as follow: 

```JSON
    "terraform.path": "/usr/local/bin/terraform",
    "terraform.codelens.enabled": true,
    "terraform.format": {
        "ignoreExtensionsOnSave": [
            ".tfsmurf"
        ]
    },
    "terraform.languageServer": {
        "enabled": true,
        "args": []
    },
    "terraform.indexing": {
        "enabled": false,
        "liveIndexing": false,
        "delay": 500,
        "exclude": [
            ".terraform/**/*",
            "**/.terraform/**/*"
        ]
    },
    "[terraform]": {
        "editor.formatOnSave": true,
    },
    "terraform.telemetry.enabled": false,
}
```

Thanks.

**Comment by Dovry** [comment]
Could you share more of the variables file? That does not look like the correct way to define vars, but it's hard to judge with the little info provided.

**Comment by fredflev** [comment]
@Dovry 

I am using terraform.tfvars to define variable declared in variables.tf :

For e.g: 

![image](https://user-images.githubusercontent.com/42792052/65686313-ab969700-e096-11e9-98e8-e762339f21dd.png)

**Comment by fredflev** [comment]
@dovry
We are using `terraform.tfvars` to implement variables defined in `variables.vars`
E.g:

**Comment by fredflev** [comment]
@Dovry
We are using `terraform.tfvars` to implement variables defined in `variables.vars`

E.g:

`terraform.tfvars`

```HCL
resource_group_name = "myuatrg"

subdomain_name = "uat"
```


`variables.tf`

```HCL
variable "resource_group_name" {
  type        = string
  description = "The name of the resource group."
}

variable "subdomain_name" {
  type        = string
  description = "The name of the DNS subdomain"
}

```

**Comment by Dovry** [comment]
Does it still complain when you save the files?
![image](https://user-images.githubusercontent.com/15201298/65686627-97867180-e065-11e9-8732-0c5a4a619eb7.png)
Also, which version and IDE are you using?

**Comment by fredflev** [comment]
I am using vscode: 

```
 code --version
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
```

```
tfswitch 
✔ 0.12.9 *recent
Switched terraform to version "0.12.9" 
```

```bash
terraform --version
Terraform v0.12.9
```

And the version of the extension is the latest: 
```
code --list-extensions --show-versions | grep -i terra
mauve.terraform@1.4.0
ms-azuretools.vscode-azureterraform@0.2.4
run-at-scale.terraform-doc-snippets@0.4.0
```

**Comment by Dovry** [comment]
```
$:code --version
1.38.1
b37e54c98e1a74ba89e03073e5a3761284e3ffb0
x64
```
updated from v0.12.7 to latest, still works
```
$:terraform --version
Terraform v0.12.9
```
and extensions
```
$:code --list-extensions --show-versions | grep -i terra
mauve.terraform@1.4.0
mindginative.terraform-snippets@2.1.0
```
Maybe try disabling the other extensions, and/or reinstalling this one?

**Comment by fredflev** [comment]
I've reinstalled the mauve.terrafrom extension only and uninstall the rest: 

Same issue: 

![image](https://user-images.githubusercontent.com/42792052/65736635-41213d80-e10e-11e9-8f3e-1d3a7bca1d47.png)

Are you using the language server or you are using indexing? 
I found out that the issue disappear if I am not using the language server. 

Is there a way to tweek the rules from the language server by adding some configuration to vscode `settings.json`?

**Comment by oswalya** [comment]
I have the same behaviour and was also not able to figure out what is causing this. Any help appreciated!

**Comment by skupjoe** [comment]
Is there any way to ignore such errors?

**Comment by skupjoe** [comment]
Language server didn't fix all of these for me. And brought some others. Is there any way to toggle language checking entirely?

**Comment by xandroxygen** [comment]
Any progress on this, or a way to ignore `.tfvars` files?

**Comment by opsline-ilan** [comment]
Hate to +1, but I have this exact issue. Seems like a huge problem because using separate tfvars is the only sane way to organize terraform.

**Comment by hixus** [comment]
same issue also

**Comment by BongoEADGC6** [comment]
+1

**Comment by weseven** [comment]
Same issue, even after uninstalling e reinstalling the extension:

```
--> code --version
1.40.1
8795a9889db74563ddd43eb0a897a2384129a619
x64
```

```
--> terraform --version
Terraform v0.12.13
```

```
--> code --list-extensions --show-versions | grep terr
mauve.terraform@1.4.0
```

**Comment by ImIOImI** [comment]
I have this problem as well:
mauve.terraform@1.4.0
run-at-scale.terraform-doc-snippets@0.4.0
mindginative.terraform-snippets@2.1.0

1.40.1
8795a9889db74563ddd43eb0a897a2384129a619
x64

**Comment by pengzhisun** [comment]
Same issue:

```
--> sw_vers                                                                                     
ProductName:    Mac OS X
ProductVersion: 10.15.1
BuildVersion:   19B88
```
```
--> code --version
1.40.1
8795a9889db74563ddd43eb0a897a2384129a619
x64
```
```
--> terraform --version                                                                        
Terraform v0.12.16
+ provider.azurerm v1.36.1
```
```
--> code --list-extensions --show-versions | grep terr
mauve.terraform@1.4.0
ms-azuretools.vscode-azureterraform@0.3.0
```
```json
--> settings.json
{
	"terraform.path": "/usr/local/bin/terraform",
    "terraform.codelens.enabled": true,
    "terraform.format": {
        "ignoreExtensionsOnSave": [
            ".tfsmurf"
        ]
    },
    "terraform.indexing": {
        "enabled": false,
        "liveIndexing": false,
        "delay": 500,
        "exclude": [
            ".terraform/**/*",
            "**/.terraform/**/*"
        ]
    },
    "terraform.languageServer": {
        "enabled": true,
        "args": []
    },
    "[terraform]": {
        "editor.formatOnSave": true,
    },
    "terraform.telemetry.enabled": false
}
```

**Comment by amongil** [comment]
Same issue:

`sw_vers                                                                                                                                                                           
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G87`

`code --version                                                                                                                                                                    
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64`

`terraform --version                                                                                                                                                               
Terraform v0.12.16
+ provider.azurerm v1.36.0
`

`code --list-extensions --show-versions | grep terr                                                                                                                                
mauve.terraform@1.4.0
`

`settings.json = {
...
"terraform.languageServer": {
        "enabled": true,
        "args": []
    },
    "terraform.indexing": {
        "enabled": false,
        "liveIndexing": false
    }
...
}`

**Comment by dboitard** [comment]
same issue

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88

$ code --version
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64

$ terraform --version
Terraform v0.12.16

$ code --list-extensions --show-versions | grep terr
4ops.terraform@0.1.7
laszer25.terraform-azure-autocomplete@0.0.1
mauve.terraform@1.4.0
ms-azuretools.vscode-azureterraform@0.3.0
run-at-scale.terraform-doc-snippets@0.4.0

settings.json 
{
...
   "terraform.indexing": {
        "enabled": false,
        "liveIndexing": false,
        "delay": 500,
        "exclude": [
            ".terraform/**/*",
            "**/.terraform/**/*"
        ]
    },
    "terraform.languageServer": {
        "enabled": true,
        "args": []
    },
..
}

**Comment by smartshader** [comment]
Same issue:
```
--> [System.Environment]::OSVersion                                                                                     
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.17763.0 Microsoft Windows NT 10.0.17763.0
```
```
--> code --version
1.40.2
f359dd69833dd8800b54d458f6d37ab7c78df520
x64
```
```
--> terraform --version                                                                        
Terraform v0.12.16
```

```
--> code --list-extensions --show-versions | Select-String -Pattern 'terra'
mauve.terraform@1.4.0
```

**Comment by pbrit** [comment]
Disabling `languageServer` in `sessions.json` makes this error disappear. 

#### Settings.json
```json
"terraform.languageServer": {
        "enabled": false
}
```

This issue can be closed.

**Comment by pbrit** [comment]
`terraform-lsp` doesn't support `tfvars` format.
Open Issue for that: https://github.com/juliosueiras/terraform-lsp/issues/39

**Comment by fredflev** [comment]
This issue is related to `terraform-lsp` and not `vscode-terraform`. 
A `terraform-lsp`  issue has been opened here:  juliosueiras/terraform-lsp#39

**Comment by AaronNBrock** [comment]
I understand this this problem is related to the language server, however would it be possible to get a work around of having the language server disabled just for files of type `*.tfvars`?

(admittedly I don't have a good understanding of language servers, so maybe this question doesn't make sense)

**Comment by pecigonzalo** [comment]
> Disabling `languageServer` in `sessions.json` makes this error disappear.
> 
> #### Settings.json
> ```json
> "terraform.languageServer": {
>         "enabled": false
> }
> ```
> 
> This issue can be closed.

But breaks everything else as tf12 is not supported without LSP afair.
