### ISSUE TITLE
Incorrectly highlighting Strings inside maps

### ISSUE THREAD

**Issue by cristim** [mauve/vscode-terraform#22]
In the below screenshot I'd expect the strings inside the map to be colored green as well (I'm using the Kimbie Dark theme).

![image](https://cloud.githubusercontent.com/assets/95209/25286471/27f1439e-26be-11e7-80f8-5d51b930b377.png)

Later edit: the comments inside maps are also colored incorrectly

**Comment by mauve** [comment]
Hi, I am currently focussing on making the index-related features better and I am unsure if I will have time to have a look at this _soonishly_.

**Comment by haad** [comment]
Hi do you have any pointers where to look in `syntax.json` I could have a look.

**Comment by mauve** [comment]
@haad no sorry `syntaxes/terraform.json` still baffles me everytime I open it. I think the bug might be somewhere here: https://github.com/mauve/vscode-terraform/blob/master/syntaxes/terraform.json#L69-L94 but I dont really understand this format that well. If you know of a good debugging or authoring tool for it that would be awesome to know about!

**Comment by haad** [comment]
I had a look and for me this was not an issue with your extension but rather conflict with another one.`wholroyd.hcl` when I removed this extension everything started to work again.

**Comment by haad** [comment]
@mauve this one was fixed also.

**Comment by mauve** [comment]
@haad thanks for reminding me, will update changelog so that it is correct in the next release
