### ISSUE TITLE
Support #region #endregion for code folding

### ISSUE THREAD

**Issue by adamrushuk** [mauve/vscode-terraform#224]
I can see previous issues #48 and #63 on code folding are now closed, but this doesn't work for me using the latest version (1.4.0).

This is very useful for larger files, so please could you be looked into?

**Comment by mauve** [comment]
I guess you have switched to using the language-server? In that case you need to ping https://github.com/juliosueiras/terraform-lsp

**Comment by adamrushuk** [comment]
Ok will do, thanks
