### ISSUE TITLE
Vault Terraform Provider missing from Language Server

### ISSUE THREAD

**Issue by infa-bsurber** [mauve/vscode-terraform#228]
Terraform language server is missing the vault provider:
https://github.com/terraform-providers/terraform-provider-vault

**Comment by troyready** [comment]
I think this should be filed against https://github.com/juliosueiras/terraform-lsp , right?

(it's not the only one missing; I believe https://github.com/terraform-providers/terraform-provider-kubernetes needs to be added as well)

**Comment by infa-bsurber** [comment]
Ah, will make another issue there just in case, thanks

**Comment by infa-bsurber** [comment]
dupe'd here: https://github.com/juliosueiras/terraform-lsp/issues/34

**Comment by juliosueiras** [comment]
This kind of issue is strictly of vscode-terraform, since terraform-lsp work by communication with the provider binary, so when you do `terraform init` on the folder, it grab the provider binary, which allow the lsp to provide autocompletion, error checking, etc

**Comment by infa-bsurber** [comment]
Oh figured out the causing issue for this actually: I wasn't doing "terraform init" in my directory with the tf files.
I use terragrunt for environment/workspace management so I had never done a "terraform init" in my tf files directory.
