### ISSUE TITLE
0.12 - version  - linter marks var as typo

### ISSUE THREAD

**Issue by idanakeneo** [mauve/vscode-terraform#236]
when writing terraform 0.12 code ,
for example var.example,
is being marked as a typo which is not the case in terraform 0.12
if you add ${}  it shows as correct but it terraform 012 it is not needed for vars anymore .

**Comment by moyuanhuang** [comment]
![image](https://user-images.githubusercontent.com/14947870/67544641-26110180-f6ab-11e9-82f7-3cc609006a8e.png)

Having the same problem. I'm assuming the plugin version that supports 0.12 code (v 1.4.0)  is merged and released according to this [comment][https://github.com/mauve/vscode-terraform/pull/200#issuecomment-524652595]. Is seems like a bug in the syntax check

**Comment by moyuanhuang** [comment]
nvm you'll have to run the following command in the vs code command palette and restart vs code to enable 0.12 syntax support:

```
Terraform: Enable/Disable Language Server
```

@idanakeneo fyi

**Comment by idanakeneo** [comment]
Confirmed - it indeed solves the issue @moyuanhuang 


Thanks
