### ISSUE TITLE
locals not recognized in security groups

### ISSUE THREAD

**Issue by chillum** [mauve/vscode-terraform#241]
Hi,

I have a manifest like this:
```terraform
locals {
  tags = {
    Test = "123"
  }
}
resource "aws_security_group" "swarm_sg" {
  tags = local.tags
}
```

this is a valid manifest, tflint is okay with it, I can run the manifest with terraform. but for some reason vscode's terraform mode displays this error:`Unknown token: 7:10 IDENT local.tags`

**Comment by mauve** [comment]
this is terraform 0.12 syntax and requires you to switch to the language server

**Comment by chillum** [comment]
thanks, works like a charm
