### ISSUE TITLE
Terraform 0.12 support without LSP

### ISSUE THREAD

**Issue by aliusmiles** [mauve/vscode-terraform#254]
@mauve Would you mind highlighting how much work needs to be done to convert plugin to terraform 0.12 syntax using 'old-way' without language server? @juliosueiras has done an outstanding work, but  lsp-terraform is still quite rough around the edges and there were no updates to it for about a month now. Totally understandable, as there are other important priorities in life besides developing open source apps, but watching slow death of great plugin is kinda painful and I'm sure quite a lot of users rely heavily on this plugin in their daily work.

So it would be really helpful to have some pointers on where to start and where to look, if you could spare some time of course :) Unfortunately I'm not that familiar with javascript to do reverse-engineering from scratch and there doesn't seem to be anybody to pick up development, but I hope with some guidance it'll be easier to at least try.

**Comment by sfertman** [comment]
@aliusmiles, you're absolutely right. Activating LSP should be a user's choice. After updating my Terraform code to 0.12, I basically lost all functionality that mattered in a vscode plugin besides syntax highlighting. Which in itself would be fine but the highlights some code as mistakes based on lagging data. It cannot deal with writing in real time and if I paste more than 5 lines it cranks up CPU usage to 300 percent and then I need to kill it. Only to be restarted again. 

This is a great extension for 0.11 but using LSP is a worse regression compared with having no language support at all. 

I sincerely hope that the devs would reconsider not making LSP optional.

**Comment by aliusmiles** [comment]
Well, to be honest, it's possible to disable LSP but without it there is virtually no 0.12 support at all.. 

I guess it's simply unfortunate that from the whole lot of VSCode and terraform users there seems to be only two guys present experienced with javascript/go and able to work on extension/language server, and both just got other priorities in life. That is totally understandable and that's what open source is - if you don't like it, you fork it and do it yourself. But I'm rather wondering what happened to all those authors of major PRs to this extension and where all of them disappeared  :-) 

So far the only hope to get it all working is to wait for author of LSP to get healthy and to find time to fix it. I've tried to poke around in extension's codebase, but it's way beyond my limited js knowledge. I had a suspicion that regenerating `hcl-hil.js` might help, but obviously it's not that simple...

**Comment by juliosueiras** [comment]
@sfertman could you paste the flow that you did that cause the CPU spike here https://github.com/juliosueiras/terraform-lsp/issues ? since I mostly test the lsp in vim(since that is my editor) and I haven't seen CPU spikes, so it would be nice if I double check if there is a vscode specific issue, also what the current features that you need for terraform, since I am working on 0.0.10 for bug fixes, and several new features this/next week

**Comment by aliusmiles** [comment]
@juliosueiras glad you feeling better! Please don't take this current issue as a voice to discard or diminish your efforts, you've done a terrific job already, thanks a lot, btw! It's just a futile attempt to try some alternative solution while you don't have spare time to work on LSP as you are busy with, well, your life ;)

P.S. I'll post some info on cpu issue in https://github.com/juliosueiras/terraform-lsp/issues/47

**Comment by juliosueiras** [comment]
@aliusmiles k, will look into it =)

**Comment by sfertman** [comment]
@juliosueiras  Thanks for you reply. It pretty much happens consistently whenever I modify many lines at once or write too fast. My project is not very big but too big to paste it in an issue. I will try to reproduce a CPU "spike" (actually a "step") with a self contained example and post an issue. 

Re. features: the one that bothers me the most is jump to definition. I guess this is the one I use enough to notice the lack of it. There are some other little things e.g. `file("<path>")` will say that no file exists but terraform plan has no problem finding it, or that `terraform.workspace` is not recognized. I mean, those are just nice-to-haves but it's distracting to see your tf file painted red when there's nothing wrong with it...

Finally, don't take my rant the wrong way; I know writing an LSP server is no walk in the park (tried it myself a while ago). I think `vscode-terraform` made a mistake here by basing language support on an experimental project without making sure (testing / active contrib) that it actually works as expected in vscode. 

Wish you all the best.

**Comment by juliosueiras** [comment]
@sfertman can you try v0.0.10 ? and see if the CPU spike is still happening

**Comment by kevingimbel** [comment]
How can I update to v0.0.10? I'm having the same issues, CPU goes crazy whenever I open a terraform project

**Comment by aliusmiles** [comment]
@kevingimbel just run 'Terraform: Install/Update Language server' from command palette.

**Comment by kevingimbel** [comment]
That didn't solve it. Even in a small tf project (only ~10 tf files) it goes crazy.

**Comment by juliosueiras** [comment]
@kevingimbel what os you on?

**Comment by kevingimbel** [comment]
macOS Mojave 10.14.6 (18G103)

**Comment by juliosueiras** [comment]
@kevingimbel can you try removing `~/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-lsp` and `~/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-lsp.tar.gz` and doing a install again of 0.0.10?

**Comment by kevingimbel** [comment]
@juliosueiras it seems to be fixed! The CPU spikes are gone, thank you!
