### ISSUE TITLE
EOF breaks the highlighting

### ISSUE THREAD

**Issue by kamsz** [mauve/vscode-terraform#26]
Multiline strings are breaking the further highlighting.

![image](https://cloud.githubusercontent.com/assets/2961450/26793763/7e3f734a-4a1f-11e7-969c-6a80ba2e3c19.png)

**Comment by dani-lanaya** [comment]
This breaks for me when the EOF block is indented. Removing the indentations resolved the issue.

**Comment by mauve** [comment]
in the example the heredoc ends with `]EOF` (indented by 4) I think the `EOF` should be on its own line (indented to index 0)?
