### ISSUE TITLE
VSCode + adsf-vm

### ISSUE THREAD

**Issue by pecigonzalo** [mauve/vscode-terraform#279]
I was trying to use this extension from WSL2 but it seems formating and potentially other things, do not work.

```
2020-02-14 12:02:19:632 [INFO ] formatting-provider: running 'terraform fmt' on '/home/pecigonzalo/Workspace/src/3tier-app/infrastructure/domain.tf'
2020-02-14 12:02:19:633 [ERROR] formatting-provider: formatting failed. TypeError: Cannot read property 'path' of null
```

I was going through the code to try and find the reason, and I believe its related to the `findInPath` method. https://github.com/mauve/vscode-terraform/blob/master/src/runner.ts#L201

It's using `process.env.PATH` which I don't know how it behaves in VSCode Remote, but before attempting a fix I'm trying to understand why we are doing this. 
We should be able to use `terraform` directly without finding a path and letting the user set a full path if not in PATH.

There is also a "version" finder here: https://github.com/mauve/vscode-terraform/blob/master/src/runner/version.ts which I cant find documentation for. As far as I understand the code it checks the version defined by terraform is the same as the one in the runner. IMO this is the job of the CLI and not of these extensions. 

I also find we can define `path` and `paths` as extension options, but the usage of `paths` is not documented.

If you could help me out with these questions I might be able to put a PR to fix the path for VSCode Remote.

**Comment by pecigonzalo** [comment]
I found the problem is related to https://asdf-vm.com/ (and potentially any terraform version manager) due to that https://github.com/mauve/vscode-terraform/blob/master/src/runner/version.ts and version checkers.

Because `terraform version` does not run in the context of the workspace folder, `asdf` is unable to detect what version to use.

**Comment by pecigonzalo** [comment]
I believe we should move the function `getTerraformVersion` to be a method of the class `Runner`, it would make sense given the runner runs a `version` command to get it. 

Then it should use the `cwd` constant to run in the correct folder. Let me know your thought and ill craft a PR.

**Comment by jthegedus** [comment]
@pecigonzalo This is a problem I would like to solve. Perhaps there's a change we can make to the asdf-terraform plugin that performs the required setup to make this work 🤔

**Comment by pecigonzalo** [comment]
I think defaulting this tool to `terraform` in `terraform.path` is the best approach.

**Comment by jthegedus** [comment]
@pecigonzalo Mine was already set to `terraform`

![Screen Shot 2020-03-21 at 11 35 44 am](https://user-images.githubusercontent.com/20798510/77215436-2f25d200-6b68-11ea-9093-f1f045066541.png)

and yet I still had this issue. I might be misunderstanding your previous explanations

**Comment by pecigonzalo** [comment]
Did you run vscode in the context of the folder?

**Comment by jthegedus** [comment]
The Terraform codefiles are subfolders in the VSCode project.

I did just see this error, so something new to investigate

```
2020-03-23 11:49:31:139 [ERROR] formatting-provider: formatting failed. TypeError: Cannot read property 'path' of null
```

**Comment by pecigonzalo** [comment]
Yeah, that was the error I was getting, you also need to set a global terraform version in `asdf` I think, because the version checking code might not respect the `path` config. 🤷‍♂

**Comment by jthegedus** [comment]
Thanks, that worked. So for future people running into this issue:
1. check Terraform is set in the VSCode Ext path field as in the screenshot above
2. set your `asdf global terraform` version
3. restart VSCode (literally CMD + Q quit the application as a restart on macOS didn't do this for me).
