### ISSUE TITLE
Indexing support - Cannot find resource definition from another file

### ISSUE THREAD

**Issue by Burgyn** [mauve/vscode-terraform#291]
Hi,

I don't know if I'm doing something wrong, but I probably indexing support doesn't work.

I have 2 files in the same directory:
1. `main.tf`

```
provider "azurerm" {
  version         = "=2.1.0"
  features {}
}
resource "azurerm_resource_group" "platform" {
  name     = "my-platform-rsg"
  location = "westeurope"
}
```

2. `application-insights.tf`

```
resource "azurerm_application_insights" "ai" {
  name                = "$my-platform-ai"
  resource_group_name = azurerm_resource_group.platform.name
  location            = azurerm_resource_group.platform.location
  application_type    = "web"
}
```

In second `application-insights.tf` file is resource `azurerm_resource_group.platform` unknown. Goto Definition / Show references doesn't work.
![image](https://user-images.githubusercontent.com/5930822/76598358-0320a600-6503-11ea-8c86-c7df5ad21bd0.png)

I tried change setting to:

```json
"terraform.indexing": {
    "enabled": true,
    "liveIndexing": true,
    "delay": 500
}
```

but without a change.
What am I doing wrong?

Thanks.

**Comment by tenwit** [comment]
That's tf 0.12 code, which isn't supported by indexing. Disable it and use the language server instead.

**Comment by Burgyn** [comment]
Hi,
thanks for your advice.
