### ISSUE TITLE
Validate returns "Validation failed, more information in the output tab" but output tab is empty

### ISSUE THREAD

**Issue by zxaos** [mauve/vscode-terraform#34]
Using terraform 0.10.4 and vscode-terraform 0.0.18 with vscode user settings:

```
    "terraform.lintPath": "/usr/local/bin/tflint",
    "terraform.path": "/usr/local/Cellar/tfenv/0.5.2/versions/0.10.4",
    "terraform.formatOnSave": true
```

**Comment by mauve** [comment]
`terraform.path` should be the path to the executable. I will have a look wrt the empty output tab.

**Comment by zxaos** [comment]
Oops! Fixed. But even adjusting `terraform.path` to the correct path, the behaviour is the same.

**Comment by mauve** [comment]
You might also need to set `terraform.templateDirectory`:

```js
  // A relative path to where your templates are stored relative to the workspace root.
  "terraform.templateDirectory": "templates",
```

`terraform validate` only works when given a directory containing `.tf` files. It does not work if given directory of directory for example. This is a restriction I will work around in the plugin (I will open a separate issue).

However when validation fails for me I actually get output in the output tab (did you select *Terraform*?):

![screen shot 2017-10-06 at 9 27 07 am](https://user-images.githubusercontent.com/795800/31268188-75b41a84-aa7b-11e7-80c6-3b723a43ef25.png)

**Comment by zxaos** [comment]
Got it now - adding the `templateDirectory` made it start working! Thanks for the help.
