### ISSUE TITLE
"Sorry, but there is no formatter for 'terraform'-files installed." with portable ZIP instance of VSCode

### ISSUE THREAD

**Issue by jlucktay** [mauve/vscode-terraform#42]
I am running VSCode (x64) v1.18.0 with v0.0.19 of this extension.

VSCode is being run from the extracted contents of a portable ZIP. It is not "installed" on the machine, just unzipped from [the portable ZIP](https://az764295.vo.msecnd.net/stable/dcee2202709a4f223185514b9275aa4229841aa7/VSCode-win32-x64-1.18.0.zip) into a directory and executed from there.

I'm running the portable ZIP version due to a lack of admin rights, on a client-provided laptop for my current project. Admin rights may or may not be attainable, so I have to work without them for the time being.

When I choose the "Format Document" option from the command palette, I get the following error:

`Sorry, but there is no formatter for 'terraform'-files installed.`

I have also tried setting the path to the `terraform.exe` in VSCode settings like so:
```json
    "terraform.path": "C:\\bin\\terraform.exe",
```
This doesn't make any difference, unfortunately.

**Comment by mauve** [comment]
That seems weird, I will try tonight when I come home.

**Comment by jlucktay** [comment]
@mauve any joy with this?

**Comment by mauve** [comment]
sorry no haven't had the time to test yet. But re:Invent is over so it
should get more chill now.

On Thu, Nov 30, 2017 at 11:36 AM, James Lucktaylor <notifications@github.com

**Comment by joshma** [comment]
Having the same issue - let me know if there's anything I can do to help fix. VSCode 1.18.1, MacOS 10.13.1, Terraform extension 0.0.19

**Comment by mauve** [comment]
It turns out this is because I am not using the correct way of implementing formatters. I will try and push a fix soonishly.

**Comment by mauve** [comment]
Hi, this should now be fixed in version 0.0.20, please give it a try! Thanks for your patience.

**Comment by jlucktay** [comment]
Looks good to me. Thank you very much!
