### ISSUE TITLE
resource auto-completion

### ISSUE THREAD

**Issue by 28mm** [mauve/vscode-terraform#43]
Hi,

I'm wondering what your thoughts are on extending auto-completion for resources and data sources. I did a quick hack to test this out (screenshot below). Do you have input / would you consider a PR to accomplish this?

![screen shot 2017-12-13 at 7 37 08 pm](https://user-images.githubusercontent.com/22941656/33974484-760ada7a-e03d-11e7-9a1f-783630b76c45.png)

A few thoughts of mine, in no particular order:

  * I'm collecting resource types by scraping [https://www.terraform.io/docs/index.html](https://www.terraform.io/docs/index.html). the `vim-terraform` project seems to accomplish the same by cloning github repos that match `terraform-provider-*`, and searching for resource definitions in the source.
  * `CompletionItem.documentation` can present abbreviated documentation and link to `terraform.io`
  * It may be possible to auto-populate required properties, but I haven't given this much thought.

Curious to have your thoughts and interested in putting a PR together if this approach seems reasonable.

**Comment by mauve** [comment]
I have been playing with similar approaches (either scraping the webpage or just scraping the source code directly). That seems to be the only approach right now :/

The current completion provider is real hack (https://github.com/mauve/vscode-terraform/blob/4020355654682131383f6152e4d0cde789a98fb3/src/providers.ts#L39-L53) I would welcome any improvement to it.

I have a branch which I sadly haven't really completed yet which makes the index much more complete (https://github.com/mauve/vscode-terraform/tree/rework-indexing) which would also benefit from a better completion-provider.

Anyway, any help is appreciated.

**Comment by mauve** [comment]
there is pullrequest for this now #51
