### ISSUE TITLE
not formatting on save

### ISSUE THREAD

**Issue by odedpriva** [mauve/vscode-terraform#46]
Hi, 

formatting on save stopped working in the last few days. 

using vscode Version 1.19.0
plugin 0.0.20  
Terraform v0.11.1

**Comment by chadbean** [comment]
Having the same issue.

**Comment by taganaka** [comment]
Make sure to have the following settings:

```
"terraform.format.enable": true,
"editor.formatOnSave": true
```

This worked for me.

**Comment by taganaka** [comment]
Oh, that was already discussed here: https://github.com/mauve/vscode-terraform/issues/45

**Comment by chadbean** [comment]
Thanks @taganaka -- I think this can be closed now @odedpriva?

**Comment by odedpriva** [comment]
@taganaka thanks. 
@chadbean, yep, that helped
