### ISSUE TITLE
Do not format tfvariable file

### ISSUE THREAD

**Issue by en0x** [mauve/vscode-terraform#47]
Seems like with the version of `0.0.20` the `"terraform.formatVarsOnSave"` does no longer exist. 
How with the new version I can disable formatting for `tfvars` files but leave it for `tf` files?

thank you

**Comment by mauve** [comment]
Sorry for breaking this feature, I will bring back that feature in 0.0.21 very soon.

**Comment by en0x** [comment]
@mauve thank you

**Comment by RowdyHowell** [comment]
For anyone in the future that missed the reference issue above like I did, the new way to do this is:

```
"terraform.format": {
    "ignoreExtensionsOnSave": [ ".tfvars" ]
}
```
