### ISSUE TITLE
Code folding of resources does not correctly handle inline HEREDOC blocks

### ISSUE THREAD

**Issue by domhnallw** [mauve/vscode-terraform#48]
When viewing a resource in a Terraform file, if it contains a HEREDOC block (for example, an IAM policy), the code folding doesn't work - the closing curly brace is correctly matched but when folding the resource the HEREDOC block remains unfolded.

Unfolded:

![image](https://user-images.githubusercontent.com/10363775/35335412-6fb0a010-010d-11e8-8c30-7ecab42ad2ef.png)

Folded:

![image](https://user-images.githubusercontent.com/10363775/35335445-87f668da-010d-11e8-894c-f30e686450fb.png)

VSCode version: 1.19.2, x64, Linux (Ubuntu 16.04)
plugin version: mauve.terraform 0.0.20

**Comment by mauve** [comment]
thanks for reporting this bug, I will try and see if I can figure out how to solve it, this should be possible to do using just the configuration so if somebody wants to give it a try, all help is greatly appreciated

**Comment by mauve** [comment]
this has previously been impossible to implement (I think) but should now be possible to implement using [https://code.visualstudio.com/docs/extensionAPI/vscode-api#FoldingRangeProvider](FoldingRangeProvider)
