### ISSUE TITLE
Autocomplete & syntax highlighting not working

### ISSUE THREAD

**Issue by srivishesh** [mauve/vscode-terraform#49]
Hello,

Thanks for the extension. I was looking forward to use it to reduce a lot of typing with terraform. 
I was trying this plugin on a mac (v10.13.33), VSCode (v1.20) and Terraform (v 0.11.3) and the autocomplete or syntax highlighting doesn't work at all. 

Tried to reinstall this and VS Code as well but no luck.

Then I tried to install the other Terraform autocomplete extension (which is in beta) and it works as expected. 

Can you please advise if I am missing something? 

![image](https://user-images.githubusercontent.com/10403178/35977600-77346c0c-0cdb-11e8-93da-e249cef1fd79.png)

**Comment by fmedery** [comment]
Same problem here on Ubuntu 17.10 with the latest version of vs-code: no linter, no color, not auto formatting.

**Comment by mauve** [comment]
- this plugin does not currently support auto-complete (there is a pull-request for it though so hopefully soon)
- the linting requires that you install the `tflint` tool
- the formatting requires that you install `terraform`

- please specify which version you are using
- please provide some more information about your setup.

feel free to reopen after providing some more information which will enable me to check what is wrong

**Comment by fmedery** [comment]
Strange, I just tested again today with the latest version code (updated yesterday) and it starts working again. I did not change anything but code version. 
versions installed on the computer :
```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

 which terraform

/usr/local/bin/terraform
 terraform --version
Terraform v0.11.3

 which tflint
/usr/local/bin/tflint

tflint --version
TFLint version 0.5.4

code --version
1.21.0
9a199d77c82fcb82f39c68bb33c614af01c111ba
x64
```
