### ISSUE TITLE
on osx, cmd key shortcut

### ISSUE THREAD

**Issue by mllanes** [mauve/vscode-terraform#54]
This is more of a question than an issue; is there any way to disable the "cmd" shortcut that automatically opens the browser with the terraform documentation for the resource that the cursor is in in the editor?

**Comment by mauve** [comment]
That does not happen on my machine :)

@ranga543 is that done by auto-completion?

**Comment by ranga543** [comment]
@mauve it doesn't happen on my machine either and @mllanes I don't think we implemented that feature.

**Comment by mauve** [comment]
@mllanes do you have any other extensions installed?

**Comment by mllanes** [comment]
@mauve I have [Terraform Autocomplete](https://marketplace.visualstudio.com/items?itemName=erd0s.terraform-autocomplete) and [Terraform](https://marketplace.visualstudio.com/items?itemName=mauve.terraform) of course. 
It only happens in .tf files and when cursor is on top of a TF resource

**Comment by mauve** [comment]
The feature must come from the other extension then Terraform Autocomplete.
This GitHub is for the (main) Terraform extension.

Am 14.03.2018 18:12 schrieb "Marcos Llanes" <notifications@github.com>:
