### ISSUE TITLE
Started to reformat on save after update to 0.0.23 version

### ISSUE THREAD

**Issue by mskonovalov** [mauve/vscode-terraform#56]
It ignores settings and reformats on Save event in case of autosave is enabled

**Comment by mauve** [comment]
please tell me which settings you are referring to?

what is the value of the setting `terraform.format.formatOnSave`

**Comment by mskonovalov** [comment]
First of all, thing I don't like is that behaviour changed after update for me.
Secondly, I tried to turn it off with several options I found on the internet

"[terraform]": {
        "editor.formatOnSave": false
    },

terraform.formatOnSave

None of them worked.

First of all I think this option is better make off by default.
Secondly you should add this option explicitly on readme.md

**Comment by mauve** [comment]
It is explicitly documented in the settings dialog (as are all settings),
and it is also noted in the changelog.

The setting is called terraform.format.formatOnSave.

VSCode should show a unknown setting warning for terraform.formatOnSave.

Am 14.03.2018 00:24 schrieb "Mikhail Konovalov" <notifications@github.com>:
