### ISSUE TITLE
extra lines, removal of tabs on latest build

### ISSUE THREAD

**Issue by sce81** [mauve/vscode-terraform#57]
i've been using this for a while now - its great.
but i've noticed recently on save, all of my tabs get deleted and every line in the document is spaced by 2.
removing the module corrects the issue
This happens as soon as i save my document

eg:

```
variable "foo"                      {}
variable "bar"                      {}

becomes
variable "foo" {}


variable "bar" {}
```

**Comment by mauve** [comment]
You probably want to disable terraform.format.formatOnSave (or just go with
the flow and let terraform decide your formatting)



Am 13.03.2018 18:52 schrieb "sce81" <notifications@github.com>:

**Comment by sce81** [comment]
yes, this does seem to resolve the issue - its only been a problem since the latest VScode (mac) release

**Comment by mauve** [comment]
Formatting used to be default a couple of releases ago but was disabled due
to bugs. Bugs are now gone so it was reenabled by default again.

Am 13.03.2018 20:25 schrieb "sce81" <notifications@github.com>:
