### ISSUE TITLE
Bug/Preference: New line added, inconsistently, between variable declarations

### ISSUE THREAD

**Issue by sforcier** [mauve/vscode-terraform#58]
## Steps to reproduce
If I start with this...
```
# The SNS topics to use for alarms when missing data, insufficient data, data has returned to OK status (health service)
variable "sns_arn_alarm" {}
variable "sns_arn_alarm_insufficient" {}
variable "sns_arn_alarm_ok" {}
```

## Actual results
When I save the file it gets turned into this...
```
# The SNS topics to use for alarms when missing data, insufficient data, data has returned to OK status (health service)
variable "sns_arn_alarm" {}

variable "sns_arn_alarm_insufficient" {}
variable "sns_arn_alarm_ok" {}
```

## Expected results
Personally, I'd like the lot to stay together, but if there are reasons to require the new line then I'd prefer it to be applied consistently, like this...
```
# The SNS topics to use for alarms when missing data, insufficient data, data has returned to OK status (health service)
variable "sns_arn_alarm" {}

variable "sns_arn_alarm_insufficient" {}

variable "sns_arn_alarm_ok" {}
```

**Comment by mauve** [comment]
If you run `terraform fmt` what result do you get then?

Am 15.03.2018 12:37 schrieb "sforcier" <notifications@github.com>:

**Comment by sforcier** [comment]
The same results... sorry for the bother. I'll open an issue with Terraform. Thanks for the fast reply.

**Comment by mauve** [comment]
@sforcier thanks for verifying
