### ISSUE TITLE
terraform.format [on-save]: Failed: 'Error: write EPIPE'

### ISSUE THREAD

**Issue by rbarna1** [mauve/vscode-terraform#59]
Multiple Win10 machines running VSCode and Terraform 0.23.  
The linter does not seem happy, as all on-save events and validate fail.
terraform.validate and terraform.lint simply report 'Failed', while the on-save event reports Error: write EPIPE.

Any ideas if there are known incompatibilities that prevent the plugin from doing validation, linting?

**Comment by mauve** [comment]
If you run the command manually (from a command-line) what do you get then?

Am 16.03.2018 13:20 schrieb "Bob" <notifications@github.com>:

**Comment by rbarna1** [comment]
Thanks @mauve, you nailed it.  When I ran terraform validate from Terminal the error was perfect: :)
Error: 1 error(s) occurred:

* provider.azurerm: no suitable version installed
  version requirements: "(any version)"
  versions installed: none

Didnt know I needed to install the providers separately from terraform (our azurerm script IS working), so I'll look into how do to that.
