### ISSUE TITLE
Auto Save and Auto Format conflict

### ISSUE THREAD

**Issue by jmccollum-bw** [mauve/vscode-terraform#60]
This is more of a feature request than an actual bug, but with Auto Save enabled in vscode and auto formatting on in Terrafom there are some issues. 

When typing in a new line, pausing for a second will cause auto format to run and will move incomplete code around, remove lines that are needed, etc. I've found that if I put in an illegal char, that will prevent auto formatting to run until I'm ready for it to auto format. 

Both features are great, but it would be nice if there was a delay on auto formatting that could be configured or invoke formatting on keystroke or button vs on save.

**Comment by mauve** [comment]
you can disable format on save for terraform and invoke formatting manually using the command `Format Document`, `Shift-Alt-F` on windows?

this is actually the reason why format on save is disabled for auto-save, however I had a lot of users complaining about missing the format on auto-save feature.

**Comment by jmccollum-bw** [comment]
That works.  I really do like the formatter, it was just too quick in being helpful!
