### ISSUE TITLE
Path expansion for terraform binaries broken

### ISSUE THREAD

**Issue by phekmat** [mauve/vscode-terraform#62]
It looks like #50 broke my configuration (formatting, linting, etc no longer work) since my binaries are in my home dir (e.g. `~/bin/terraform`) and `child_process.execFile` doesn't spawn a shell

Changing that to `/real/path/to/bin/terraform` gets things going again, but it would be nice to support at least home directory expansion again.

**Comment by IronFarm** [comment]
This is also broken for me on Windows but however I specify the binary path, it doesn't work.

**Comment by mauve** [comment]
@IronFarm what is the path to Terraform for you and what is your configuration? Can you please post what does and doesn't work exactly?

**Comment by IronFarm** [comment]
How embarrassing, it appears to work now. It seems you have to quit and reopen VS Code for the settings to update.

However, it claims to successfully run `fmt` but the file doesn't change.

```
2018-10-04 08:53:06:177 [INFO ] formatting-provider: running 'terraform fmt' on 'c:\Users\user.name\Documents\terraform\main.tf'
2018-10-04 08:53:06:178 [INFO ] runner: Running terraform cwd='C:\Users\user.name\AppData\Local\Programs\Microsoft VS Code' path='terraform11' (version: 0.11.8) args=[fmt, -]
2018-10-04 08:53:07:073 [INFO ] file-system-watcher: Indexed file:///c%3A/Users/user.name/Documents/terraform/main.tf
2018-10-04 08:53:07:939 [INFO ] runner: Running terraform succeeded.
```

**Comment by garthk** [comment]
> However, it claims to successfully run fmt but the file doesn't change

I'm seeing this, also, after manually specking my path to `terraform` and re-launching Code.

**Comment by mauve** [comment]
I don't really know what to do with this issue as it seems to be working again, please feel free to reopen if the issue persists.

Thanks for using my plugin, sorry that I couldn't be of more help.

**Comment by phekmat** [comment]
I can still reproduce this on 1.3.12 if the terraform binary is not in my PATH (unless I skimmed too quickly, the `runner` helper introduced (https://github.com/mauve/vscode-terraform/commit/1d4e52bcafdbb458a137cf90ca0d8c84a9d5d132) searches the `PATH`, but doesn't do path expansion for `~`). 

That said, since my binary is actually in my PATH, that change fixed my use-case so thanks :smiley: .
