### ISSUE TITLE
Support #region #endregion for code folding

### ISSUE THREAD

**Issue by jcrben** [mauve/vscode-terraform#63]
These are supported in core vscode for some languages (https://stackoverflow.com/a/46597272/4200039 and https://github.com/Microsoft/vscode/issues/12146) - I suggest adding `#region` support. 

Also if the autoformatter did not force a space before the trailing `#endregion` comment I'd prefer that. 

I tried adding something like https://github.com/Microsoft/vscode/blob/6c421d85528d4ddb37dcb167b7a442e348f51378/extensions/javascript/javascript-language-configuration.json to https://github.com/mauve/vscode-terraform/blob/master/syntaxes/terraform.json and https://github.com/mauve/vscode-terraform/blob/master/terraform.configuration.json but it didn't work.

**Comment by mauve** [comment]
just back from vacation will see if I can find some time this or next week

**Comment by unacceptable** [comment]
Mention was accidental.  Please disregard.
