### ISSUE TITLE
How are you keeping docs up to date?

### ISSUE THREAD

**Issue by erd0s** [mauve/vscode-terraform#64]
Hey there,

I created another vscode plugin for autocomplete since I couldn't get yours working, but now I see with the recent updates that yours is way better than what I had so I'm going to bow out and leave this with you, however one of my challenges was keeping the documentation up to date and I was wondering how you were doing it?

I had started this: https://github.com/erd0s/terraform-scrape which I used to get all the data from the online docs, if you don't already have something in place I'd be happy to modify what I have to fit with your plugin, either way I'd be interested to know how you're doing it because it killed me when I was trying!

Cheers

**Comment by mauve** [comment]
https://github.com/mauve/vscode-terraform/blob/master/src/data/README.md points to the repo which scrapes the docs.

I would welcome pull-requests and improvements to both this plugin and the repo https://github.com/ranga543/terraform-docs-scrape which the autocomplete functionality was done by @ranga543 

Kind regards,

Mikael
