### ISSUE TITLE
Unable to get terraform validate to work

### ISSUE THREAD

**Issue by tonyxiao** [mauve/vscode-terraform#65]
I'm getting the following error

```
terraform.validate: Failed:

Error: No Terraform configuration files found in directory: /Users/tony/Code/afedulov/terraform-fargate/terraform/templates
```

My workspace directory is here - https://github.com/afedulov/terraform-fargate/tree/master/terraform

Running `terraform validate` on the command line seems to work just fine. So i'm not sure why this is giving me issues.

**Comment by mauve** [comment]
the default configuration assumes that the terraform templates are stored in a folder called `templates` (see https://github.com/mauve/vscode-terraform/blob/master/package.json#L108-L112) relative to the workspace root.

In your case you probably want to change that configuration to `terraform` (you can do it in a per-workspace configuration if you want to)
