### ISSUE TITLE
Pressing Ctrl opens documentation

### ISSUE THREAD

**Issue by MOZGIII** [mauve/vscode-terraform#67]
Pressing Ctrl (just Ctrl!) opens documentation.

I'd like to only happen when I *Ctrl+click*, as everywhere else it works.

I'm using Ubuntu 16.04.

**Comment by mauve** [comment]
I don't think this is a feature we provide. Which other plugins do you have
installed?

MOZGIII <notifications@github.com> schrieb am Mi., 11. Apr. 2018, 08:38:

**Comment by MOZGIII** [comment]
Indeed, seems like the issue is with `erd0s.terraform-autocomplete`, not this plugin. Thanks for helping me out.
This plugin is great.

**Comment by mauve** [comment]
This plugin has auto complete since the last release so maybe you don't
need the other one still.

MOZGIII <notifications@github.com> schrieb am Mi., 11. Apr. 2018, 09:05:
