### ISSUE TITLE
Link to Terraform docs

### ISSUE THREAD

**Issue by jkodroff** [mauve/vscode-terraform#68]
Would love to see contextual links to the Terraform documentation.

For example:
```hcl
resource "aws_s3_bucket" "my_bucket" { ...
```

Ctrl-clicking on `aws_s3_bucket` would take the user to: https://www.terraform.io/docs/providers/aws/r/s3_bucket.html

**Comment by mauve** [comment]
fixed in 1.0.3

**Comment by mauve** [comment]
Thanks.

**Comment by joshschmitter** [comment]
Is there a reason was implemented using static data in `src/data/*.json` instead of dynamically generating the link using terraform's url path convention?  I'm thinking about creating a PR for this but don't want to go through the effort if that idea was already shot down.

**Comment by mauve** [comment]
I don't remember, it might have been that the urls were not predictable in all cases, but that might no longer be true.

If you want to verify:

In the vim-terraform repo there is a collection of json files which together list all resource and data types, you could write a script which parses those json files and just check the dynamically generatef urls if they are correct for a large enough subset of types. If true, I think we should go with that approach.

**Comment by joshschmitter** [comment]
Thanks for the tip!  I see a few vim-terraform repos.  Are you referring to hashivim/vim-terraform?

**Comment by mauve** [comment]
Sorry I mean the repo mentioned in this line:  https://github.com/mauve/vscode-terraform/blob/completion-wip/tasks/auto-completion-data.task.js#L16
