### ISSUE TITLE
Add option to disable codeLens just from Terraform plugin

### ISSUE THREAD

**Issue by garo** [mauve/vscode-terraform#73]
Please add a configuration setting to disable codeLens feature from the plugin.

**Comment by mauve** [comment]
Why? What is the problem?

**Comment by garo** [comment]
It's simply that I don't like the way it adds the "%d references" extra lines, especially when I look files which mainly define variables.
![image](https://user-images.githubusercontent.com/381921/39417983-624ebbc0-4c60-11e8-9b14-edfcec4e9a91.png)

There are however other modules using codelens features which I still find valuable, so I'd rather not disable the codelens feature entirely from VS Code.

It might work if the codelens annotations would be positioned on the right side on the same line instead of adding entirely new lines, which I feel distracting.

**Comment by CamelCaseNotation** [comment]
I have this set to "false" and yet the codeLens are still showing for Terraform. Release 1.3.5

**Comment by CamelCaseNotation** [comment]
Restarted vscode and also re-opened each `.tf` file. Had to disable codeLens in order for them to stop showing up
