### ISSUE TITLE
v1.0.3 doesn't work

### ISSUE THREAD

**Issue by MartynasZilinskas** [mauve/vscode-terraform#74]
Newest version extension doesn't work: `1.0.3`.

**Expected behavior:**
- Auto-completion
- Syntax highlighting

**Actual behavior:**
Auto-completion and syntax highlighting doesn't work.

**VSCode version:** 1.22.2

**Last working version**: 1.0.1

**Comment by MartynasZilinskas** [comment]
It works. Thanks for fast fix. 👍

**Comment by mauve** [comment]
Awesome thanks for using my plugin.
