### ISSUE TITLE
Document Link support on macOS

### ISSUE THREAD

**Issue by ArtemK007** [mauve/vscode-terraform#79]
Hi!

Thanks for the extension! Would be nice if `Document Link support` can be disabled. Currently on my my mac (High Sierra, 10.13.3, VS Code version 1.23.0, terraform extension v1.0.5) just pressing cmd key with cursor hovered over resource type opens link to terraform docs in browser, kinda annoying, if you just want to copy text (cmd+c), for example, but your cursor is on some resource, which leads to opening link. Not sure if it should work this way. Also didn't found any options to disable this behavior.

Thanks!

**Comment by mauve** [comment]
which other plugins to do you have installed, the document link support done by this plugin requires Cmd+Click

**Comment by ArtemK007** [comment]
🤦

why I didn't tested it first? Looks like `Terraform Autocomplete (erd0s.terraform-autocomplete)` extension is guilty. Thanks!
