### ISSUE TITLE
fmt on save includes plugin warning

### ISSUE THREAD

**Issue by pmcatominey** [mauve/vscode-terraform#8]
The warning is printed by Terraform when starting up as I've got a plugin overridden.

![image](https://cloud.githubusercontent.com/assets/918856/22460346/58f7d7de-e79c-11e6-98e0-23fd8ddeb771.png)

**Comment by mauve** [comment]
I guess you get the same warning when you run "terraform fmt" directly? Can you try and figure out if there is a combination of command line arguments for "terraform fmt" which removes the warning?

**Comment by mauve** [comment]
The plugin consumes all of `stdout` and replaces the current editor contents with it. The warning is written to `stdout` and is therefore indistinguishable from the actual content. This is most certainly a bug in `terraform` which should write warnings to `stderr`.
