### ISSUE TITLE
'Go to Definition' from tfvars

### ISSUE THREAD

**Issue by borekb** [mauve/vscode-terraform#80]
Code navigation seems to be working nicely in `.tf` files but when I try to go to a `.tfvars` file and invoke _Go to Definition_ on one of the variables, I am not taken to its definition. Would be great if this worked.

**Comment by mauve** [comment]
started to work on that this morning :D hopefully might be able to create a new release over the weekend

**Comment by borekb** [comment]
Awesome :)
