### ISSUE TITLE
'locals' keyword is not syntax-highlighted

### ISSUE THREAD

**Issue by borekb** [mauve/vscode-terraform#81]
It seems that the `locals` keyword is missing syntax highlighting:

![image](https://user-images.githubusercontent.com/101152/39812739-24a1382c-538e-11e8-88ea-304d3cfa243d.png)

**Comment by borekb** [comment]
Locals generally seem to be less supported than variables, for example, Go to Definition doesn't work for me.

**Comment by mauve** [comment]
goto definition is not supported for locals yet, will fix in a follow-up PR
