### ISSUE TITLE
Linting failed

### ISSUE THREAD

**Issue by hniemann** [mauve/vscode-terraform#82]
When I try to lint I get Linting failed, more informations in the output tab.
In the output tab is only tarreform.lint: Failed:
I try to set "terraform.lintpath": "/usr/local/bin/tflint" but same failure.

In Terminal tflint works.

TFLint version 0.5.4
Terraform Extension: 1.0.6

**Comment by mauve** [comment]
- can you post your the `terraform` part of your settings?

**Comment by mauve** [comment]
Are your tf-files in a directory called 'templates' relative to workspace root?

The linter is called with 'terraform.templateDirectory' as the directory.

**Comment by hniemann** [comment]
No... but when I try to set the path like this I get the same error

/test/projects <- workspace
/test/projects/project1 <- set as templateDirectory  "terraform.templateDirectory": "project1",

**Comment by mauve** [comment]
I just reread the source :D and it turns out that `terraform.templateDirectory` is ignored when calling `tflint`. However I just published *1.0.7* which fixes a minor bug that did render an empty string instead of the error message.

**Comment by hniemann** [comment]
Now I get the error terraform.lint: Failed: Error: spawn tflint ENOENT

**Comment by mauve** [comment]
The path to tflint is wrong. Remember that the settings key names are case sensitive.

**Comment by mauve** [comment]
Think I have figured it out. I will try tonight.

**Comment by mauve** [comment]
fixed in 1.0.8, please reopen if not fixed; thanks for the bugreport
