### ISSUE TITLE
CodeLens references - constrain to cwd?

### ISSUE THREAD

**Issue by richeney** [mauve/vscode-terraform#83]
Mikael, that is a great extension - thank you. One question - for the CodeLens references, should they show references within the current working directory only?  If I have multiple directories within my workspace (with copies of the files) then the reference count goes up.

**Comment by mauve** [comment]
yes the index is currently `global` which is suboptimal. I will see if I can find time this weekend to constrain it per workspace folder.

**Comment by richeney** [comment]
By the way I am creating a series of Terraform labs for our UK Azure partners.  I’m recommending your extension as one of the ones to install.  It is so useful, so thanks again.

The labs will be in the https://aka.ms/citadel/workshops once I’ve published them.

**Comment by mauve** [comment]
cool, thanks for recommending it. let me know if there are any improvements you could think of.

**Comment by richeney** [comment]
Be careful what you wish for!! 😃

**Comment by richeney** [comment]
Excellent work Mikael!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
