### ISSUE TITLE
Codelense reference not found when variable is in list

### ISSUE THREAD

**Issue by jvhoof** [mauve/vscode-terraform#86]
Very nice plugin I was surprised about the references popping up this morning. It makes Terraform life a lot easier! 

One reference it couldn't find is in the below. The address_space for a Azure VNET is a list. Once I remove the list the reference is detected.

File 1:
resource "azurerm_virtual_network" "vnet" {
  name                = "${var.PREFIX}-VNET"
  address_space       = ["${var.vnet}"]
  location            = "${azurerm_resource_group.resourcegroupvnet.location}"
  resource_group_name = "${azurerm_resource_group.resourcegroupvnet.name}"
}

File 2:
variable "vnet" {
  description = ""
  default     = "172.30.104.0/24"
}

**Comment by mauve** [comment]
thanks for giving me a repro-case, I will try and fix this over the weekend.

**Comment by mauve** [comment]
I cannot reproduce this, I added the two files as stated (just copy-pasted and the reference is correctly detected for me):

![vnet](https://user-images.githubusercontent.com/795800/40271945-32e099cc-5ba5-11e8-9b45-674d12129c98.PNG)
![vnet2](https://user-images.githubusercontent.com/795800/40271946-33002f26-5ba5-11e8-9c4c-a51e89f02cbc.PNG)

**Comment by jvhoof** [comment]
I tried it in VS Code Insiders and it worked. So I reinstalled the extension on my normal VS Code and now it works fine. thanks for the quick response.

**Comment by mauve** [comment]
thanks for verifying.
