### ISSUE TITLE
plugin not work on mac

### ISSUE THREAD

**Issue by Coffee-Bene** [mauve/vscode-terraform#88]
vscode version:1.23.1
vscode-terraform:1.1.2
![image](https://user-images.githubusercontent.com/26565257/40764815-ea310176-64dc-11e8-83db-5fbd1ba7d331.png)

**Comment by Coffee-Bene** [comment]
I  try to press control + space,It does not work. If thers are some dependencies that I do not install...

**Comment by Coffee-Bene** [comment]
sorry,I found the problem that the plugin should be enabled in workspace...

**Comment by mauve** [comment]
no problem, thanks for using my plugin.
