### ISSUE TITLE
Error on saving a list variable value

### ISSUE THREAD

**Issue by vendoran** [mauve/vscode-terraform#9]
line throwing the error is:
vpc_security_groups = ['sg-xxxxxxxx'] (I masked the id value)

Error:
![image](https://cloud.githubusercontent.com/assets/3491696/22596026/6e646966-e9ef-11e6-85e5-8d9f66a6e79d.png)

**Comment by vendoran** [comment]
Same thing happens when I specific it as a default value:
`variable "vpc_security_groups" {
  type        = "list"
  description = "List of VPC Security Group IDs to apply to the instance"
  default     = ['sg-78fb5e05']
}`

**Comment by mauve** [comment]
that looks like ansi color codes, do you have color codes in your source code?

**Comment by vendoran** [comment]
Nevermind PEBCAK - syntax is vpc_security_groups = ["sg-xxxxxxxx"] instead - double quotes, not single quotes.  per https://www.terraform.io/intro/getting-started/variables.html

Thanks for the response though.
