### ISSUE TITLE
Adding extra commas to arrays

### ISSUE THREAD

**Issue by bstascavage** [mauve/vscode-terraform#90]
When defining an array in a resource, the extension adds a commas to the last element, like so:

```
  cidr_blocks = [
    "${module.lookup.cidr_block_1}",
    "${module.lookup.cidr_block_2}",
  ]
```

**Comment by mauve** [comment]
is this added by the auto-completion feature or by the formatting?

if you invoke `terraform fmt ${path_to_file}` what does it say?

**Comment by mauve** [comment]
@bstascavage ping

**Comment by bstascavage** [comment]
Sorry for the delay.  You're right, it seems like `terraform fmt` is the one adding the extra comma, not your extension.  So this is a bug with Terraform, it looks like.

**Comment by mauve** [comment]
thanks for verifying
