### ISSUE TITLE
Unable to see Resource Type for Symbol

### ISSUE THREAD

**Issue by chrisduong** [mauve/vscode-terraform#92]
Hi,

I don't know if I configured something differently. When I pressed Ctrl + R to browse symbols, I cannot see the Resource Type. This is hard to choose the correct Symbol Type I want.

Please see the attached picture.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/1848882/41086277-1854f62c-6a6c-11e8-9e3f-df29f9e1fe09.png">

**Comment by mauve** [comment]
You are right this is a bug, I will try and fix it this week.
