### ISSUE TITLE
Failed: Cannot find module '../hcl-hil.js'

### ISSUE THREAD

**Issue by zunlihu** [mauve/vscode-terraform#93]
I just want to try the vscode-terraform project and clone you repository. 
But when I want to debug the project, there are something wrong.
In the Extension host, it shows **"Cannot find module '../hcl-hil.js'".**
I have found that there is not such a file, can you teach me how to get such a file?
I am a beginner for vsc extension. Thanks for you attention and patience.

**Comment by mauve** [comment]
Hi

You need to follow the instructions at https://github.com/mauve/vscode-terraform/blob/master/BUILDING.md, specifically "First build" to get started with development.

Happy hacking, looking forward to your contribution.

**Comment by zunlihu** [comment]
When I run "npm run gulp",there are still some errors.
![image](https://user-images.githubusercontent.com/21325921/41265332-49be1dae-6e24-11e8-996b-b9607589697b.png)

**Comment by mauve** [comment]
Building requires docker to be installed.

**Comment by zunlihu** [comment]
Thanks a lot! 
At first, thanks a lot for you patient guidance. The problem I have mentioned above have been solved! But there are still errors, just as the attachment shows.o(╥﹏╥)o

I think there maybe something wrong inside the code. But I haven't changed the source code.

I will look through the source code carefully, and it will be very grateful if you can give me some ideas about this.




----- 原始邮件 -----
发件人: "Mikael Olenfalk" <notifications@github.com>
收件人: "mauve/vscode-terraform" <vscode-terraform@noreply.github.com>
抄送: "zunlihu" <zunlihu@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期二, 2018年 6 月 12日 下午 1:46:20
主题: Re: [mauve/vscode-terraform] Failed: Cannot find module '../hcl-hil.js' (#93)

Building requires docker to be installed.

Sent from my iPhone

> On 12. Jun 2018, at 03:38, zunlihu <notifications@github.com> wrote:
> 
> When I run "npm run gulp",there are still some errors.
> 
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/mauve/vscode-terraform/issues/93#issuecomment-396472575
--

**Comment by mauve** [comment]
No problem glad to help. I do not think you can use attachment when answering to issues via mail, at least I cannot see anything.

**Comment by zunlihu** [comment]
Because I am not convenient to use github online.

Can you see the following error information now?

**Comment by mauve** [comment]
No I cannot see anything, please just write comments on website instead.

**Comment by zunlihu** [comment]
The error information is showed as follows.
![image](https://user-images.githubusercontent.com/21325921/41294193-015fc542-6e8a-11e8-800d-0e01ad094015.png)

**Comment by mauve** [comment]
after running `npm install` what version of vscode API was downloaded as part of the `npm postinstall` step? (the step is executed automatically, but it prints what it installs)

**Comment by zunlihu** [comment]
It's the same with you.
![image](https://user-images.githubusercontent.com/21325921/41325429-d5382280-6eec-11e8-9847-953a922e76b7.png)

**Comment by mauve** [comment]
I figured it out `vscode.workspace.workspaceFolders` is `undefined` if vscode is started without a workspace folder opened, so this code fails. I pushed this commit https://github.com/mauve/vscode-terraform/commit/e4620854e3d0d1684eca3299ab93d4bca9d5dcbb which should fix your issue.

**Comment by zunlihu** [comment]
Yes. It works successfully. 
But I have found that there may be some problems in resource type autocompletion. When I have typed "aws", it doesn't show all aws resource list, which you can see in the following picture.
![image](https://user-images.githubusercontent.com/21325921/41359186-8917ece4-6f5c-11e8-9e47-05214601e928.png)

Do I need some special trigger action? or  it just have some small bugs?

**Comment by mauve** [comment]
autocompletion is still somewhat buggy, but Ctrl+Space should trigger
autocompletion manually.

**Comment by zunlihu** [comment]
hhh  Got it!
If I want to get the parse information or result of *.tf file, which part should I pay more attention on? hcl-hil folder?

**Comment by mauve** [comment]
if you want the raw AST you can use `parseHcl` from `src/index/hcl-hil.ts`. If you want a more high-level AST you probably want to use the `FileIndex` class. The plugin keeps a list of up-2-date `FileIndex` instances per `WorkspaceFolder`, you can use `IndexLocator` use get hold of one, here is an example:

https://github.com/mauve/vscode-terraform/blob/master/src/index/providers.ts#L8

**Comment by zunlihu** [comment]
Thanks a lot!!
