### ISSUE TITLE
Extension does not appear to work in Ubuntu 18.04

### ISSUE THREAD

**Issue by icornett** [mauve/vscode-terraform#94]
Hello,
I noticed that I can't seem to get any of the features of your plugin working in Ubuntu 18.04.  I've tried checking the settings for the app, and there doesn't appear to be anything related to your extension that I can see to enable.  It works fabulously on my Windows partition, but seems to do next-to-nothing here.

VS Code version: 1.24.1
Extension version: 1.1.2
` lsb_release -a`
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

Thanks for the great work!

**Comment by mauve** [comment]
do you have another terraform plugin installed? e.g. `erd0s.terraform-autocomplete` or any other HCL plugin?

**Comment by icornett** [comment]
Hi Mikael,

I do have three Terraform plugins installed, the same configuration as in Windows 10.


Terraform 1.1.2

Azure Terraform 0.2.0

Advanced Terraform Snippets Generator 2.0.1


________________________________

**Comment by mauve** [comment]
ok I will see if I can reproduce

**Comment by icornett** [comment]
I think I just figured it out, it's probably a VSCode configuration issue.  It keeps (correctly) detecting the file as HCL instead of Terraform and it's causing the plugin not to fire.  Alternatively, you could configure it to work with HCL and still prefer TF, but that might get you a bunch more bugs due to other variants.

**Comment by mauve** [comment]
if you have several plugins which all support the same files (e.g. *.tf) you can manually configure your vscode file type to plugin assignments, this might be necessary in cases where you have multiple conflicting plugins.


Are you sure that these were the only relevant plugins installed?

- Terraform 1.1.2
- Azure Terraform 0.2.0
- Advanced Terraform Snippets Generator 2.0.1

Thanks for following up on the issue.

**Comment by icornett** [comment]
I just saw this one when I searched HCL, not under Terraform:

wholroyd.hcl




Ian Cornett | Cloud DevOps Engineer
(425) 605-7952<tel:4256057942> |  icornett@redapt.com<mailto:icornett@redapt.com>
[redapt-logo-red-black]


________________________________
