### ISSUE TITLE
Find Reference sending me to incorrect file

### ISSUE THREAD

**Issue by heldersepu** [mauve/vscode-terraform#96]
Here is my tree
```
├── environment
│   ├── bucket11.tf
│   └── variables.tf
│
├── regional
│   ├── bucket22.tf
│   └── variables.tf
│
├── example.tf
├── output.tf
└── variables.tf
```

When I click F12 on the `enabled` that is on file:
`resource "aws_s3_bucket" "sample_bucket1111" `
it should send me to the variables file that is on the same directory (environment/variables.tf)
but instead it sends me to the one outside.

That tree structure is here: 
https://github.com/heldersepu/hs-scripts/tree/master/TerraForm

**Comment by mauve** [comment]
Hmm, I always thought that the variables had to be unique but terraform does not seem to complain. I even added a another (duplicate) in `environment/variables.tf`.

However I do not think that this behaviour by the real terraform is correct. You have duplicates of these variables in the same module, how do you specify different values? Changing the default of one of the variables has no effect in my tests, unless changing the one defined in the root `variables.tf`.

Removing the variable from the root file breaks the templates.

How do you use these templates?

```
$ cd /tmp
$ git clone .../hs-scripts.git
$ cd hs-scripts/TerraForm
$ terraform init
# success
$ terraform plan
# No changes. Infrastructure is up-to-date.
$ terraform plan -var enabled=1
  + aws_s3_bucket.sample_bucket12629
  + aws_subnet.app1
  + aws_vpc.myvpc
$ # enabled = 1 in environment/variables.tf
$ git diff
diff --git a/TerraForm/environment/variables.tf b/TerraForm/environment/variables.tf
index b790202..f89fad2 100644
--- a/TerraForm/environment/variables.tf
+++ b/TerraForm/environment/variables.tf
@@ -1,5 +1,5 @@
 variable "enabled" {
   type        = "string"
   description = "to enable or not to enable"
-  default     = 0
+  default     = 1
 }
$ terraform plan
# No changes. Infrastructure is up-to-date.
$ git checkout environment/variables.tf
$ # enabled = 1 in regional/variables.tf
$ git diff
diff --git a/TerraForm/regional/variables.tf b/TerraForm/regional/variables.tf
index feb1986..f469f6b 100644
--- a/TerraForm/regional/variables.tf
+++ b/TerraForm/regional/variables.tf
@@ -1,4 +1,4 @@
 variable "enabled" {
   type    = "string"
-  default = 0
+  default = 1
 }
$ terraform plan
# No changes. Infrastructure is up-to-date.
```

*vscode-terraform* keeps one index per workspace folder, within one index every resource/variable needs to be unique. For now I do not support modules (yet) which means that some things are not scoped correctly.

**Comment by mauve** [comment]
I have opened a new issue which more correctly describes the underlying issue, closing this now.
