### ISSUE TITLE
fmt error on data "template_file" with inline script

### ISSUE THREAD

**Issue by dhoffi** [mauve/vscode-terraform#97]
See attached screenshot.
<img width="782" alt="screenshot" src="https://user-images.githubusercontent.com/10828920/41464893-3619f410-709c-11e8-879b-ca7a9141fee8.png">

**Comment by mauve** [comment]
what happens if you run `terraform fmt ${file-path}` directly?

**Comment by dhoffi** [comment]
it doesn't complain ... no errors on the commandline

**Comment by mauve** [comment]
1. Are you using the same terraform version in VSCode and on the command line?
1. Can you please post the relevant output of the "Output (Terraform)" tab?
1. Is the code available somewhere?

**Comment by dhoffi** [comment]
cannot reproduce it right now, sorry.
But the thing that hassled me (and I tought maybe it was related)
is that if I have an inline block in a terraform template like:

```
data "template_file" "bbr-pcf-pipeline-tasks-vars" {
  template = <<CONTENT
skip-ssl-validation: true
opsman-url: https://((opsman_url))
git-private-key: ((pipeline-repo-key.private_key))
backup-container-name: ((backup-container-name))
azure-storage-account: ((storage-account.username))
azure-storage-account-key: ((storage-account.password))
pcf-env: ((pcf-env))
starttime: ((starttime))
CONTENT
}
```

and I want to fold this, it only gets foldet up to the first `<<CONTENT` and not the whole `data` section

**Comment by mauve** [comment]
code-folding on here-documents has not been possible due of lack of the required APIs in vscode, however since one or two releases that is now possible to support. I will close this bug as it should work. Feel free to reopen. There is another bug open with the code folding support for heredocs, feel free to subscribe to that one.

Thanks for using my plugin.
