### ISSUE TITLE
Auto-completion duplicates

### ISSUE THREAD

**Issue by heldersepu** [mauve/vscode-terraform#98]
On a similar setup to the Issue #96 I get duplicates on the Auto-completion
![image](https://user-images.githubusercontent.com/545474/41501494-611febe2-7173-11e8-9250-1fd0a2541777.png)

**Comment by mauve** [comment]
Does the variable `prevent_destroy` occur multiple times in your workspace (inside a single workspace folder)?

**Comment by heldersepu** [comment]
I updated the screenshot to use the same project as #96 ...
No the variable that shows a duplicate does not occur multiple times in a single folder.
Also some of the other variables shown on the screenshot are not accessible to sample_bucket1111

**Comment by heldersepu** [comment]
I forked the repo and been looking at the code... 
If I understand correctly this could be corrected here:
https://github.com/mauve/vscode-terraform/blob/master/src/autocompletion/completion-provider.ts#L121

My idea is to replace 
-   `return interpolationCompletions;`

with:
-    `return _.uniq(interpolationCompletions);`

But I'm having some issue running the tests on my end I get:
```
PS C:\Users\helde\Documents\GitHub\vscode-terraform> node ./node_modules/vscode/bin/test
### VS Code Extension Test Run ###
Current working directory: C:\Users\helde\Documents\GitHub\vscode-terraform
Downloading VS Code into "C:\Users\helde\Documents\GitHub\vscode-terraform\.vscode-test\stable" from: https://vscode-update.azurewebsites.net/1.24.1/win32-archive/stable
Running extension tests: C:\Users\helde\Documents\GitHub\vscode-terraform\.vscode-test\stable\Code.exe C:\Users\helde\Documents\GitHub\vscode-terraform\out\test --extensionDevelopmentPath=C:\Users\helde\Documents\GitHub\vscode-terraform --extensionTestsPath=C:\Users\helde\Documents\GitHub\vscode-terraform\out\test


Rejected cached data from file: C:\Users\helde\AppData\Roaming\Code\CachedData\24f62626b222e9a8313213fb64b10d741a326288\index-067b6f8ce629ffe57da1f2cee26dbce0.code

[main 5:02:21 PM] update#ctor - updates are disabled

Rejected cached data from file: C:\Users\helde\AppData\Roaming\Code\CachedData\24f62626b222e9a8313213fb64b10d741a326288\system-preferences-d6286f1a53f45fe602aa592b36b8d9dc.code

Error: Cannot find module '../hcl-hil.js'

Tests exited with code: 0
```

**Comment by mauve** [comment]
Hi I have updated the building/developing instructions at https://github.com/mauve/vscode-terraform/blob/master/BUILDING.md please see if you can get it work locally.

I am still a bit unsure how to solve your issue. Currently the index is **local** to a single **workspace folder** (ie. the type `vscode.WorkspaceFolder`) which may contain several folders, but you are probably correct and the index needs to be segmented into one something per actual folder.

The index contains a collection of `FileIndex`s which contains `Segments`, each segment has an id `Segment::id()` which uniquely identifies it and can be used to ensure uniqueness (the id is for example `aws_bucket.sample111` or `var.enabled`). Currently however `FileIndex` does not enforce uniqueness.

**Comment by heldersepu** [comment]
I will try the instructions see how far I can get...

**Comment by mauve** [comment]
Thanks, I updated them again this morning.

**Comment by heldersepu** [comment]
Interesting that you mentioned Mac, I usually do all my development under Windows but recently started doing some on Mac, here are the new erros under mac:
```
sepulveda at mlla1851 in ~/code/vscode-terraform on master
$ npm run clean

> terraform@1.1.2 clean /Users/hsepulveda/code/vscode-terraform
> git clean -xdf

Removing node_modules/

hsepulveda at mlla1851 in ~/code/vscode-terraform on master
$ npm install

> terraform@1.1.2 postinstall /Users/hsepulveda/code/vscode-terraform
> node ./node_modules/vscode/bin/install

internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module '/Users/hsepulveda/code/vscode-terraform/node_modules/vscode/bin/install'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terraform@1.1.2 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terraform@1.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hsepulveda/.npm/_logs/2018-06-18T12_52_41_692Z-debug.log
```

**Comment by mauve** [comment]
weird error.

I just ran the same commands on my windows machine (left the mac at the office) and at least on windows:

- `npm run clean`
- `npm install`
- `npm run watch`

works out of the box.

Just to clarify, I guess you truncated the output of `npm install`, right?

**Comment by heldersepu** [comment]
I still have to try on windows...
My last comment is form a mac and the error happens on the `npm install`

**Comment by mauve** [comment]
Will try on Mac tomorrow. I haven't done a clean build on mac for quite some time.

**Comment by mauve** [comment]
What target are you trying to run?

`npm run test` that target is only used for CI as it doesnt work if another instance of vscode is already running. For running the tests I usually just run them in vscode.

There is a launch configuration called `Launch Tests`, select it in the *Debug View* and hit `F5`

**Comment by mauve** [comment]
I have opened a new bug which describes the underlying issue, closing this bug now.

**Comment by mauve** [comment]
decided to fix this quickly and make a proper fix later
